### ISSUE TITLE
Simplify text chat experience

### ISSUE THREAD

**Issue by jancborchardt** [strukturag/nextcloud-spreedme#1]
Currently you need to go through 3 steps to be able to chat with people via text:
1. Click on the chat icon in the top right
2. Select the room
3. Click into the input field

Some means to simplify that:
- when selecting a room, automatically focus the message input field so one can just start typing
- when clicking on the chat icon, open the room chat by default
- and lastly, simply show the room chat by default in the right sidebar, along with the contacts. Not in a second sidebar.

**Comment by leonklingele** [comment]
Hey jancborchardt,

please note: This repo only contains the Spreed.ME ownCloud app, not the actual conferencing server.
What you describe is related to spreed-webrtc: https://github.com/strukturag/spreed-webrtc
So please create an issue over there :)

**Comment by jancborchardt** [comment]
Thanks, did so at https://github.com/strukturag/spreed-webrtc/issues/246 :)
