### ISSUE TITLE
Use url-safe base64 encoding for temporary passwords

### ISSUE THREAD

**Issue by fancycode** [strukturag/nextcloud-spreedme#10]
To avoid problems with clients not quoting characters correctly, temporary passwords should be encoded using the url-safe base64 alphabet defined in [RFC 4648](https://tools.ietf.org/html/rfc4648#section-5).

**Comment by leonklingele** [comment]
Implemented in b933f0e50bf07cf6b19cd5c165ad088234ddc1c4
We now accept both encoded and unencoded TPs.
