### ISSUE TITLE
error in debug

### ISSUE THREAD

**Issue by WaaromZoMoeilijk** [strukturag/nextcloud-spreedme#11]
Hey i had owncloud 8.2.2 running with spreedme on ubuntu 14.04.
Now i have owncloud 9.0 and ubuntu 14.04, with spreedme 1.4.

I changed everything to the exact same in /etc/spreed/webrtc.conf, apps/spreedme/config/config.php, apps/spreedme/extra/static/OwnCloudConfig.js and in apache virtualhost config, everything is the exact same.

(not copied the different folders/files over just the settings itself)
I can access spreedme but it doesnt sign me in as a user i also cant join a chat room.

debug gives me this error:

GET https://domain.com/webrtc/extra/static/img/spreedme.svg 404 (Not Found)w @ main.js:38H.extend.css @ main.js:39(anonymous function) @ main.js:39H.access @ main.js:39H.fn.extend.css @ main.js:39(anonymous function) @ app.js:218(anonymous function) @ app.js:218r @ main.js:41(anonymous function) @ main.js:41n @ main.js:41r @ main.js:41(anonymous function) @ main.js:42o @ main.js:41(anonymous function) @ main.js:42r @ main.js:41(anonymous function) @ main.js:41n @ main.js:41q @ main.js:42O @ main.js:42T @ main.js:42T @ main.js:42T @ main.js:42T @ main.js:42A @ main.js:42(anonymous function) @ main.js:41l.$eval @ main.js:43l.$apply @ main.js:43(anonymous function) @ main.js:41r @ main.js:41V.i @ main.js:41V @ main.js:41(anonymous function) @ main.js:45c @ main.js:43(anonymous function) @ main.js:43l.$eval @ main.js:43l.$digest @ main.js:43(anonymous function) @ main.js:43a @ main.js:42(anonymous function) @ main.js:42

Might anyone know what this is about?

Thanks for this great app
Kind regards,

Ezra

**Comment by leonklingele** [comment]
Hi Ezra,

are you absolutely sure your config files have not changed since the upgrade?

Where do you see `https://domain.com/webrtc/extra/static/img/spreedme.svg 404 (Not Found)`?
In your browser's dev console?

It would be helpful if you could paste your configuration.

**Comment by WaaromZoMoeilijk** [comment]
Yeah im quite sure, double checked everything.
I changed the secrets and my domain for security reasons as you will understand.
Keys/secrets definitely match

And indeed its the browsers dev console.
Thanks!!

> root@owncloud:/var/www/owncloud/apps/spreedme/config# cat config.php
> <?php
> /**
> - ownCloud - spreedme
>   *
> - This file is licensed under the Affero General Public License version 3 or
> - later. See the COPYING file.
>   *
> - @author Leon leon@struktur.de
> - @copyright struktur AG 2016
>   */
> 
> namespace OCA\SpreedME\Config;
> 
> class Config {
> 
>   // Domain of your Spreed WebRTC server (including protocol and optional port number), examples:
>   //const SPREED_WEBRTC_ORIGIN = 'https://myowncloudserver.com';
>   //const SPREED_WEBRTC_ORIGIN = 'https://webrtc.myowncloudserver.com:8080';
>   // If this is empty or only includes a port (e.g. :8080), host will automatically be determined (current host)
>   const SPREED_WEBRTC_ORIGIN = 'https://domain.com';
> 
>   // This has to be the same `basePath`
>   // you already set in the [http] section of the `server.conf` file from Spreed WebRTC server
>   const SPREED_WEBRTC_BASEPATH = '/webrtc/';
> 
>   // This has to be the same `sharedsecret_secret` (64-character HEX string)
>   // you already set in the [users] section of the `server.conf` file from Spreed WebRTC server
>   const SPREED_WEBRTC_SHAREDSECRET = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
> 
>   // Set to true if you want to allow access to this app + spreed-webrtc for non-registered users who received a temporary password by an ownCloud admin.
>   // You can generate such a temporary password at: /index.php/apps/spreedme/admin/tp (ownCloud admin user account required)
>   const OWNCLOUD_TEMPORARY_PASSWORD_LOGIN_ENABLED = false;
> 
>   // If 'OWNCLOUD_TEMPORARY_PASSWORD_LOGIN_ENABLED' is set to true, you also have to provide a signing key here (64-character HEX string)
>   // Generate it using `xxd -ps -l 32 -c 32 /dev/random` (better) or `openssl rand -hex 32`
>   const OWNCLOUD_TEMPORARY_PASSWORD_SIGNING_KEY = 'xxxxxxxxxxx';
> 
>   private function __construct() {
> 
>   }
> 
> }

**---------------------------------------------------------------------------------------------------------------------**

> root@owncloud:/var/www/owncloud/apps/spreedme# cat extra/static/config/OwnCloudConfig.js
> /**
> - ownCloud - spreedme
>   *
> - This file is licensed under the Affero General Public License version 3 or
> - later. See the COPYING file.
>   *
> - @author Leon leon@struktur.de
> - @copyright struktur AG 2016
>   */
> 
> // This file is loaded in WebRTC context
> 
> (function(window) {
> 
>   var OwnCloudConfig = function() {
>       return {
>           // Domain of your ownCloud server (including protocol and optional port number), examples:
>           //OWNCLOUD_ORIGIN: 'https://myowncloudserver.com',
>           //OWNCLOUD_ORIGIN: 'https://owncloud.myserver.com:8443',
>           // If this is empty or only includes a port (e.g. :8443), host will automatically be determined (current host)
>           OWNCLOUD_ORIGIN: 'https://domain.com',
>       };
>   };
> 
>   if (typeof define === "function" && define.amd) {
>       define(OwnCloudConfig);
>   } else {
>       window.OwnCloudConfig = OwnCloudConfig();
>   }
> 
> })(window);

**---------------------------------------------------------------------------------------------------------------------**

> root@owncloud:/var/www/owncloud/apps/spreedme# cat /etc/spreed/webrtc.conf
> ; Spreed WebRTC server example configuration
> 
> [http]
> ; HTTP listener in format ip:port.
> listen = 192.168.1.111:7443
> ; Full path to directory where to find the server web assets.
> root = /usr/share/spreed-webrtc-server/www
> ; HTTP socket read timeout in seconds.
> ;readtimeout = 10
> ; HTTP socket write timeout in seconds.
> ;writetimeout = 10
> ; Use basePath if the server does not run on the root path (/) of your server.
> basePath = /webrtc/
> ; Set maximum number of open files (only works when run as root).
> ;maxfd = 32768
> ; Enable stats API /api/v1/stats for debugging (not for production use!).
> ;stats = false
> ; Enable HTTP listener for golang pprof module. See
> ; http://golang.org/pkg/net/http/pprof/ for details.
> ;pprofListen = 127.0.0.1:6060
> 
> [https]
> ; Native HTTPS listener in format ip:port.
> ;listen = 192.168.1.111:443
> ; Full path to PEM encoded certificate chain.
> ;certificate = /xxxxxxx
> ; Full path to PEM encoded private key.
> ;key = xxxxxxxx
> ; Mimimal supported encryption standard (SSLv3, TLSv1, TLSv1.1 or TLSv1.2).
> ;minVersion = SSLv3
> ; HTTPS socket read timeout in seconds.
> ;readtimeout = 10
> ; HTTPS socket write timeout in seconds.
> ;writetimeout = 10
> 
> [app]
> ; HTML page title
> ;title = Spreed WebRTC
> ; Version string to use for static resources. This defaults to the server
> ; version and should only be changed when you use your own way to invalidate
> ; long cached static resources.
> ;ver = 1234
> ; STUN server URIs in format host:port. You can provide multiple seperated by
> ; space. If you do not have one use a public one like stun.spreed.me:443. If
> ; you have a TURN server you do not need to set an STUN server as the TURN
> ; server will provide STUN services.
> stunURIs = stun:stun.spreed.me:443
> ; TURN server URIs in format host:port?transport=udp|tcp. You can provide
> ; multiple seperated by space. If you do not have at least one TURN server then
> ; some users will not be able to use the server as the peer to peer connection
> ; cannot be established without a TURN server due to firewall reasons. An open
> ; source TURN server which is fully supported can be found at
> ; https://code.google.com/p/rfc5766-turn-server/.
> ;turnURIs = turn:turnserver:port?transport=udp
> ; Shared secret authentication for TURN user generation if the TURN server is
> ; protected (which it should be).
> ; See http://tools.ietf.org/html/draft-uberti-behave-turn-rest-00 for details.
> ; A supported TURN server is https://code.google.com/p/rfc5766-turn-server/.
> ;turnSecret = the-default-turn-shared-secret-do-not-keep
> ; Enable renegotiation support. Set to true to tell clients that they can
> ; renegotiate peer connections when required. Firefox support is not complete,
> ; so do not enable if you want compatibility with Firefox clients.
> ;renegotiation = false
> ; Session secret to use for session id generator. 32 or 64 bytes of random data
> ; are recommented (hex encoded). A warning will be logged if hex decode fails.
> ; You can generate a secret easily with "xxd -ps -l 32 -c 32 /dev/random".
> sessionSecret = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> ; Encryption secret protecting the data in generated server side tokens. Use
> ; 16, 24, or 32 bytes (hex encoded) to select AES-128, AES-192, or AES-256.
> ; When you change the encryption secret, stored authentications, sessions and
> ; contacts become invalid. A warning will be logged if hex decode fails. You
> ; can generate a secret easily with "xxd -ps -l 32 -c 32 /dev/random".
> encryptionSecret = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> ; Full path to a text file containig client tokens which a user needs to enter
> ; when accessing the web client. Each line in this file represents a valid
> ; token.
> ;tokenFile = tokens.txt
> ; The name of a global room. If enabled it should be kept secret. Users in that
> ; room are visible in all other rooms.
> ;globalRoom = global
> ; The default room is the room at the root URL of the servers base address and
> ; all users will join this room if enabled. If it is disabled then a room join
> ; form will be shown instead.
> ;defaultRoomEnabled = true
> ; Whether a user account is required to join a room. This only has an effect
> ; if user accounts are enabled. Optional, defaults to false.
> authorizeRoomJoin = true
> ; Whether a user account is required to create a room. This only has an effect
> ; if user accounts are enabled. Optional, defaults to false.
> ;authorizeRoomCreation = false
> ; Server token is a public random string which is used to enhance security of
> ; server generated security tokens. When the serverToken is changed all existing
> ; nonces become invalid. Use 32 or 64 characters (eg. 16 or 32 byte hex).
> serverToken = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> ; The server realm is part of the validation chain of tokens and nonces and is
> ; added as suffix to server created user ids if user creation is enabled. When
> ; the realm is changed, all existing tokens and nonces become invalid.
> serverRealm = local
> ; Full path to an extra templates directory. Templates in this directory ending
> ; with .html will be parsed on startup and can be used to fill the supported
> ; extra-\* template slots. If the extra folder has a sub folder "static", the
> ; resources in this static folder will be available as /extra/static/filename
> ; relative to your servers base URL.
> extra = /var/www/owncloud/apps/spreedme/extra
> ; URL relative to the servers base path for a plugin javascript file which is
> ; automatically loaded on web client start for all users. You can put your
> ; plugin in the extra/static folder (see above) or provide another folder using
> ; a front end webserver. Check the doc folder for more info about plugins and
> ; examples.
> plugin = extra/static/owncloud.js
> ; Content-Security-Policy HTTP response header value.
> ; Spreed WebRTC requires inline styles, WebSocket connection to itself and
> ; data: URL for images.
> ; The currently recommended CSP is:
> ;   default-src 'self';
> ;   frame-src 'self' blob:;
> ;   style-src 'self' 'unsafe-inline';
> ;   img-src 'self' data: blob:;
> ;   connect-src 'self' wss://server:port/ws blob:;
> ;   font-src 'self' data: blob:;
> ;   media-src 'self' blob:;
> ;contentSecurityPolicy =
> ; Content-Security-Policy-Report-Only HTTP response header value. Use this
> ; to test your CSP before putting it into production.
> ;contentSecurityPolicyReportOnly =
> 
> [modules]
> ; Modules provide optional functionality. Modules are enabled by default and
> ; can be disabled by setting false to their corresponding configuration.
> ;screensharing = true
> ;youtube = true
> ;presentation = true
> ;contacts = true
> 
> [log]
> ;logfile = /var/log/spreed-webrtc-server.log
> 
> [users]
> ; Set to true to enable user functionality.
> enabled = true
> ; Set users authorization mode.
> ; sharedsecret:
> ;   Validates the userid with a HMAC authentication secret.
> ;   The format goes like this:
> ;     BASE64(HMAC-SHA-256(secret, expirationTimestampInSeconds:userid))
> ; httpheader:
> ;   The userid is provided as an HTTP header. The server does not do any
> ;   validation. This usually only makes sense with a front end HTTPS proxy which
> ;   does the authentication and injects the user id as HTTP header for sessions
> ;   REST requests. In mode httpheader, allowRegistration should be false.
> ; certificate:
> ;   The userid is provided as CommonName with a certificate provided with TLS
> ;   client authentication. When you use this with a front end proxy for TLS
> ;   termination, that proxy has to validate the certificate and inject certain
> ;   headers into the proxy connection. In certificate mode the server can act as
> ;   a signing CA to sign incoming user certificate requests with a private key
> ;   when allowRegistration is true. While certificate mode offers the highest
> ;   security it is currently considered experimental and the user experience
> ;   varies between browsers and platforms.
> mode = sharedsecret
> ; The shared secred for HMAC validation in "sharedsecret" mode. Best use 32 or
> ; 64 bytes of random data.
> sharedsecret_secret = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> ; The HTTP header name where to find the userid in "httpheader" mode.
> ;httpheader_header = x-userid
> ; Full path to PEM encoded private key to use for user creation in "certificate"
> ; mode. Keep this commented if you do not want the server to sign certificate
> ; requests.
> ;certificate_key = userskey.key
> ; Full path to PEM encoded certificate to use for user validation in
> ; "certificate" mode. When allowRegistration is true and certificate_key is also
> ; set then the server will act as a CA and sign incoming user registrations and
> ; return certificates to users as registration.
> ;certificate_certificate = usersca.crt
> ; The HTTP header name where to find if the TLS client authentication was
> ; successfull. The value of this header is matched to
> ; certificate_verifiedHeaderValue and only if there is a match, the proxy
> ; handled TLS client authentication is accepted as success. Make sure to secure
> ; these headers with your front end proxy (always set them). Do not use these
> ; settings when not using a front end proxy.
> ;certificate_verifiedHeader = x-verified
> ;certificate_verifiedHeaderValue = SUCCESS
> ; The HTTP header name where to find the PEM encoded certificate authenticated
> ; by a front end proxy. With Nginx the required value is in $ssl_client_cert.
> ;certificate_certificateHeader = x-certificate
> ; The valid duration of generated certificates created in certificate mode when
> ; allowRegistration is enabled.
> ;certificate_validForDays = 365
> ; Organization to set into the created user certificates. Use a readable public
> ; name to make the certificate easily recognizable as certificate for your
> ; server so users can choose the correct certificate when prompted.
> ;certificate_organization= = My Spreed Server
> ; If enabled the server can create new userids. Set allowRegistration to true to
> ; enable userid creation/registration. Users are created according the settings
> ; of the currently configured mode (see above).
> ;allowRegistration = false

**---------------------------------------------------------------------------------------------------------------------**

> virtualhost 443
> `Header add Strict-Transport-Security: "max-age=15768000;includeSubdomains"
>     SSLEngine on
> 
> ### YOUR SERVER ADDRESS
> 
> ```
> ServerAdmin xxxxx
> ServerName xxxxx
> ServerAlias xxxxx
> ```
> 
> ### SETTINGS
> 
> DocumentRoot /var/www/owncloud
> 
> ```
> <Directory /var/www/owncloud>
> Options Indexes FollowSymLinks
> AllowOverride All
> Require all granted
> Satisfy Any
> </Directory>
> 
> Alias /owncloud "/var/www/owncloud/"
> 
> <IfModule mod_dav.c>
> Dav off
> </IfModule>
> 
> SetEnv HOME /var/www/owncloud
> SetEnv HTTP_HOME /var/www/owncloud
> ```
> 
> ### LOCATION OF CERT FILES
> 
> SSLCertificateFile /etc/xxxxx
> SSLCertificateKeyFile /etc/xxxxx
> SSLCACertificateFile /etc/xxxxx
> <Location /webrtc/>
>       ProxyPass http://192.168.1.111:7443/webrtc/
>       ProxyPassReverse /
>   </Location>
> 
>   <Location /webrtc/ws>
>       ProxyPass ws://192.168.1.111:7443/webrtc/ws
>   </Location>
> 
>   ProxyVia On
>   ProxyPreserveHost On
>   RequestHeader set X-Forwarded-Proto 'https' env=HTTPS

**Comment by WaaromZoMoeilijk** [comment]
Also i used the details of the backup'ed config files and changed them in the new config.
As i installed a fresh virtual machine with ownCloud. 

So everything is fresh, i changed the /apps/spreedme config files and apache. 
I copied the /etc/spreed/webrtc.conf to the new virtual machine since the version stayed the same and thought no changes where made to the application.

**Comment by leonklingele** [comment]
Can you please check your browser's developer console for any errors?
1. Open the Spreed.ME app in ownCloud
2. Append ?debug to the URL, i.e. https://domain.com/index.php/apps/spreedme/?debug
3. Right click on the ownCloud site
4. Click "Inspect element" (very bottom)
5. Check what it says in the console and paste it here

Also please open `https://domain.com/index.php/apps/spreedme/admin/debug` in your browser and paste the output.

Thank you

**Comment by WaaromZoMoeilijk** [comment]
Hey,

spreedme/?debug:

```
jquery.min.js?v=ef96e78…:6 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
detector.js:28 Detected Spreed WebRTC.
contentscript.js:47 Spreed WebRTC extension API injected ... 0.2.1
main.js:45 Launching ...
main.js:45 Web fonts loaded.
owncloud.js:31 Please make sure to edit your OwnCloudConfig.js file in extra/static/config(anonymous function) @ owncloud.js:31(anonymous function) @ owncloud.js:43i.execCb @ require.js:29Z.check @ require.js:18(anonymous function) @ require.js:23(anonymous function) @ require.js:8(anonymous function) @ require.js:23v @ require.js:7Z.emit @ require.js:23Z.check @ require.js:19Z.enable @ require.js:23Z.init @ require.js:17E @ require.js:14i.completeLoad @ require.js:28i.onScriptLoad @ require.js:29
app.js:231 Selected language: en
main.js:45 Bootstrapping ...
app.js:221 App runtime id: wqib37n
app.js:220 Service version: 0.24.12-1~trusty1
app.js:220 Ws URL: wss://domain.com/webrtc/ws
app.js:220 Secure Contextual Escaping: true
app.js:231 Initializing ...
app.js:223 Chrome extension is available.
PostMessageAPI.js:37 PostMessageAPI: POSTING FROM Location {hash: "", search: "?debug", pathname: "/webrtc/", port: "", hostname: domain.com"…} TO https://domain.com Object {type: "init"}
app.js:223 Screensharing support true 
main.js:39 The <keygen> element is deprecated and will be removed in M54, around October 2016. See https://www.chromestatus.com/features/5716060992962560 for more details.
app.js:221 Initial room path set, continuing to connect ...
app.js:221 Ready to connect ...
app.js:225 Checking for media access ...
app.js:225 Continue with connect after media check ...
app.js:231 Initializing complete.
app.js:221 Connecting ...
PostMessageAPI.js:37 PostMessageAPI: Got event MessageEvent {isTrusted: true, data: Object, origin: "https://domain.com", lastEventId: "", source: Window…}
app.js:219 Connector on connection open.
owncloud.js:63 OC: selfReceived Object {Type: "Self", Id: "MTQ1ODMyODY0M3xqKLHJFD)SZDWnNiUUhPRXNpNTk2aTVSeW…nPT18NkPZUC-n9Vw2lcKJFLDKJFADLKJDZnEcH6u7gpU=", Sid: "zpkUvuarATWUBawnG7KfGqjNaD2DfmbQ", Userid: "", Suserid: ""…}
app.js:222 Created new video layout renderer invisible n {}
app.js:224 Disabled video input as no video source was found.
PostMessageAPI.js:37 PostMessageAPI: Got event MessageEvent {isTrusted: true, data: Object, origin: "https://domain.com", lastEventId: "", source: Window…}
PostMessageAPI.js:37 PostMessageAPI: Got event MessageEvent {isTrusted: true, data: Object, origin: "https://domain.com", lastEventId: "", source: Window…}
```

spreedme/admin/debug:

```
Spreed.ME Version 0.1.4

Ran test #1 (testOwncloudPhpConfigFile):
   Passed without an error

Ran test #2 (testOwncloudJavascriptConfigFile):
   Passed without an error

Ran test #3 (testSpreedWebRTCAPI):
   Error: Unable to connect to WebRTC at https://domain.com/webrtc/. Did you set a correct SPREED_WEBRTC_ORIGIN and SPREED_WEBRTC_BASEPATH in config/config.php?

Some tests failed. :(
```

apache config:

```
Location /webrtc/>
      ProxyPass http://192.168.1.111:7443/webrtc/
      ProxyPassReverse /
  </Location>

  <Location /webrtc/ws>
      ProxyPass ws://192.168.1.111:7443/webrtc/ws
  </Location>

  ProxyVia On
  ProxyPreserveHost On
  RequestHeader set X-Forwarded-Proto 'https' env=HTTPS
```

Checked all the config files over and over, cant seem to find a wrong setting...

**Comment by leonklingele** [comment]
Please try to set both `SPREED_WEBRTC_ORIGIN` and `OWNCLOUD_ORIGIN` to an empty string, as you run spreed-webrtc and OC on the same host.

`const SPREED_WEBRTC_ORIGIN = '';`
and
`OWNCLOUD_ORIGIN: '',`

**Comment by WaaromZoMoeilijk** [comment]
@leonklingele
Doesn't work, do you need me to adjust the basepath as well? I guess not...
admin/debug shows the same as is ?debug. But these settings worked before, thats the odd thing...
Let me know what to test next.

Thank you for your time!

**Comment by WaaromZoMoeilijk** [comment]
Basepath also doesn't do anything for me. I'm clueless right now!

**Comment by leonklingele** [comment]
It looks like you're still running v0.1.2 of this app.
Can you please install the latest version?

**Comment by ezraholm50** [comment]
Will do just a sec will report back asap

Op zo 20 mrt. 2016 10:26 schreef leonklingele <notifications@github.com>:

> It looks like you're still running v0.1.2 of this app.
> Can you please install the latest version?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/strukturag/owncloud-spreedme/issues/11#issuecomment-198881428>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by leonklingele** [comment]
So your error log contains this line:

``` js
owncloud.js:31 Please make sure to edit your OwnCloudConfig.js file in extra/static/config
```

As you can see [here](https://github.com/strukturag/owncloud-spreedme/commit/f5286c9ceaf884a1ce8af6e9e24845a99a20b058#diff-cdd04b7cbb45195b8a2475e5eb39c9c7L31) this line got removed with v0.1.0..
Are you sure you're using the latest version of the `extra` folder?

**Comment by WaaromZoMoeilijk** [comment]
Great, I must have been using the old file itself instead of changing the details.
That indeed fixed it, works great. Sorry for this newbie error. Thanks for your time!

**Comment by leonklingele** [comment]
Thanks for using this app! :rocket:
