### ISSUE TITLE
Expiring guest account by non-admins

### ISSUE THREAD

**Issue by doc-ljp** [strukturag/nextcloud-spreedme#12]
I think this app is already very useful.
One possible improvement - at least for my use case - would be the possibility to create temporary webrtc logins by non-admins. In this way one could always invite an external user to a video conference, if necessary.

If you could point me in the right direction I may implement this feature myself.

**Comment by leonklingele** [comment]
Please see https://github.com/strukturag/owncloud-spreedme/commit/c4b8c7350b470c3c3797cf82677cbaa7da8a8a1a

Create a new group called "Spreed.ME" and add users you want to be able to create Temporary Passwords as an admin for that group.

**Comment by leonklingele** [comment]
0.1.6 was released
