### ISSUE TITLE
Spreed is getting error

### ISSUE THREAD

**Issue by apg1980** [strukturag/nextcloud-spreedme#15]
Hello, i have configured on my oc 9.0.1 running on ubuntu 14.04 your great app.
The debugging info is shown as below:
Spreed.ME Version 0.1.6

Ran test #1 (testOwncloudPhpConfigFile):
   Passed without an error

Ran test #2 (testOwncloudJavascriptConfigFile):
   Passed without an error

Ran test #3 (testSpreedWebRTCAPI):
   Passed without an error

Passed all tests. Everything seems to be set up correctly! :) 
![snip_20160504120113](https://cloud.githubusercontent.com/assets/9514965/15011176/a9d5fe38-11f0-11e6-8ef0-7bf340630bde.png)

I have used this for installing the webrtc server:
https://github.com/strukturag/spreed-webrtc/wiki/Ubuntu-Repository

Can u give mi some tips to debug the issue?
Btw. the webrtc log shows no errors.

**Comment by leonklingele** [comment]
Can you please check your browser's developer console for any errors?
1. Open the Spreed.ME app in ownCloud
2. Append ?debug to the URL, i.e. https://domain.com/index.php/apps/spreedme/?debug
3. Right click on the ownCloud site
4. Click "Inspect element" (very bottom)
5. Check what it says in the console and paste it here

Thank you :)

**Comment by apg1980** [comment]
do you mean the console output (firefox)?

```
Content Security Policy: Die Direktive 'frame-src'  sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'child-src'. <unbekannt>
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://cloud.grunet.de 'unsafe-eval'"). spreedme
Launching ... main.js:45:15198
Web fonts loaded. main.js:45:14339
Enabled mediaDevices adapter ... app.js:220:12422
Browser support for filesystem API not found. app.js:222:3612
Selected language: de app.js:231:16308
Bootstrapping ... main.js:45:15107
App runtime id: 8sr38bg app.js:221:3272
Service version: 0.24.12-1~trusty1 app.js:220:31202
"Ws URL: wss://cloud.grunet.de/webrtc/ws" app.js:220:31237
Secure Contextual Escaping: true app.js:220:31263
'mozHidden' und 'mozVisibilityState' sollten nicht mehr verwendet werden.  Bitte verwenden Sie stattdessen 'hidden' und 'visibilityState' ohne Präfix. base.js:260:13747
Initializing ... app.js:231:15115
PostMessageAPI: POSTING FROM Location → https://cloud.grunet.de/webrtc "TO https://cloud.grunet.de" Object { type: "init" } PostMessageAPI.js:50:3
Screensharing support true  app.js:223:2622
Initial room path set, continuing to connect ... app.js:221:1764
Ready to connect ... app.js:221:1568
Checking for media access ... app.js:225:13936
Continue with connect after media check ... app.js:225:13566
Initializing complete. app.js:231:15194
Connecting ... app.js:221:1298
PostMessageAPI: Got event message { target: Window → webrtc, isTrusted: false, data: Object, origin: "https://cloud.grunet.de", lastEventId: "", source: Window → spreedme, ports: MessagePortList, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false } PostMessageAPI.js:50:3
Created new video layout renderer invisible Object {  } app.js:222:19120
Firefox kann keine Verbindung zu dem Server unter wss://cloud.grunet.de/webrtc/ws aufbauen. app.js:219:23
Connector on connection error. app.js:219:1426
PostMessageAPI: Got event message { target: Window → webrtc, isTrusted: false, data: Object, origin: "https://cloud.grunet.de", lastEventId: "", source: Window → spreedme, ports: MessagePortList, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false } PostMessageAPI.js:50:3
PostMessageAPI: Got event message { target: Window → webrtc, isTrusted: false, data: Object, origin: "https://cloud.grunet.de", lastEventId: "", source: Window → spreedme, ports: MessagePortList, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false } PostMessageAPI.js:50:3
PostMessageAPI: Got event message { target: Window → webrtc, isTrusted: false, data: Object, origin: "https://cloud.grunet.de", lastEventId: "", source: Window → spreedme, ports: MessagePortList, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false } PostMessageAPI.js:50:3
getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented. jquery.min.js:5:17117
```

**Comment by apg1980** [comment]
i am using owncloud and webrtc on the same host.
ownloud is published via port 80 and webrtc on 8888.
via my sophos utm reverseproxy i am using a single ssl connection and connect everythin on the root to the owncloud server and /webrtc to the 8888.

**Comment by leonklingele** [comment]
Problem found: `Firefox kann keine Verbindung zu dem Server unter wss://cloud.grunet.de/webrtc/ws aufbauen.`

Please make sure to properly pass requests to /webrtc/ws to the webrtc server.
See our example [nginx](https://github.com/strukturag/spreed-webrtc/blob/master/doc/NGINX.txt) and [Apache](https://github.com/strukturag/spreed-webrtc/blob/master/doc/APACHE.txt) configuration.
Unfortunately I have never heard of the `sophos utm reverseproxy`, so I can't really help :(

**Comment by longsleep** [comment]
Sounds like the typical man-in-the-middle proxy which should be avoided at all cost as it usually makes things insecure. And this particular one does either not support websockets at all or the server is not set up correctly as indicated by @leonklingele

**Comment by apg1980** [comment]
i have addet a nat rule the firefox note: Firefox kann keine Verbindung zu dem Server unter wss://cloud.grunet.de/webrtc/ws aufbauen. is away,

but i got the same error above.

See console output now:

Content Security Policy: Die Direktive 'frame-src'  sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'child-src'. <unbekannt>
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://cloud.grunet.de 'unsafe-eval'"). spreedme
Launching ... main.js:45:15198
Web fonts loaded. main.js:45:14339
Enabled mediaDevices adapter ... app.js:220:12422
Browser support for filesystem API not found. app.js:222:3612
Selected language: de app.js:231:16308
Bootstrapping ... main.js:45:15107
App runtime id: aqv93d2 app.js:221:3272
Service version: 0.24.12-1~trusty1 app.js:220:31202
"Ws URL: wss://cloud.grunet.de/webrtc/ws" app.js:220:31237
Secure Contextual Escaping: true app.js:220:31263
Initializing ... app.js:231:15115
PostMessageAPI: POSTING FROM Location → https://cloud.grunet.de/webrtc "TO https://cloud.grunet.de" Object { type: "init" } PostMessageAPI.js:50:3
Screensharing support true  app.js:223:2622
Initial room path set, continuing to connect ... app.js:221:1764
Ready to connect ... app.js:221:1568
Checking for media access ... app.js:225:13936
Continue with connect after media check ... app.js:225:13566
Initializing complete. app.js:231:15194
Connecting ... app.js:221:1298
PostMessageAPI: Got event message { target: Window → webrtc, isTrusted: false, data: Object, origin: "https://cloud.grunet.de", lastEventId: "", source: Window → spreedme, ports: MessagePortList, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false } PostMessageAPI.js:50:3
Created new video layout renderer invisible Object {  } app.js:222:19120
Connector on connection error. app.js:219:1426
PostMessageAPI: Got event message { target: Window → webrtc, isTrusted: false, data: Object, origin: "https://cloud.grunet.de", lastEventId: "", source: Window → spreedme, ports: MessagePortList, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false } PostMessageAPI.js:50:3
PostMessageAPI: Got event message { target: Window → webrtc, isTrusted: false, data: Object, origin: "https://cloud.grunet.de", lastEventId: "", source: Window → spreedme, ports: MessagePortList, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false } PostMessageAPI.js:50:3
PostMessageAPI: Got event message { target: Window → webrtc, isTrusted: false, data: Object, origin: "https://cloud.grunet.de", lastEventId: "", source: Window → spreedme, ports: MessagePortList, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false } PostMessageAPI.js:50:3

**Comment by leonklingele** [comment]
I get this error message: `WebSocket connection to 'wss://cloud.grunet.de/webrtc/ws' failed: Error during WebSocket handshake: Unexpected response code: 400`
Something is still wrong with your configuration.

**Comment by fancycode** [comment]
As @longsleep wrote, the proxy most likely doesn't support WebSockets and therefore returns the `400` error for the upgrade request.

**Comment by leonklingele** [comment]
.. looks like the Sophos reverse proxy currently doesn't support WebSockets: http://feature.astaro.com/forums/17359-utm-formerly-asg-feature-requests/suggestions/4849021-websocket-support-for-waf

~ Closing, as not related to this plugin
