### ISSUE TITLE
Telephone Connection aborts after about 20 seconds

### ISSUE THREAD

**Issue by ravermeister** [strukturag/nextcloud-spreedme#16]
Hi, I've successfully installed spreed.me with owncloud.
it runs on a apache https proxy with a certificate signed by cacert.org (they are not in the browser certificate store) 

I've successful tested a telephone call between irdium (based on chromium) and chrome between 
2 windows pc's. But when I try to make a telephone call between a windows and a linux pc, the call is first established and then aborts with an error message indicating a connection problem.

the log file (of the spreed.me server instance) shows this error message:

`server 2016/05/06 21:26:16.840149 Error while reading 9 websocket: close 1006 unexpected EOF`

what can I do?

thanks in advance

**Comment by leonklingele** [comment]
This might be your problem:
http://stackoverflow.com/questions/28828332/gorilla-websocket-disconnects-after-a-minute

Apache-equivalent is the [ProxyTimeout](https://httpd.apache.org/docs/current/mod/mod_proxy.html#proxytimeout) directive.
Alternatively, try to increase the timeout directly in the [ProxyPass](https://httpd.apache.org/docs/current/mod/mod_proxy.html#workers) directive.

EDIT:
Someone had the same problem for spreed-webrtc here: https://apps.owncloud.com/content/show.php?content=174436&forumpage=0
He solved it by upgrading his webserver software. Which version of Apache are you running?

**Comment by ravermeister** [comment]
Hi, Thanks for your help, 
I'm using Apache  mpm-itk on ubuntu 14.04-lts:
`:~# apache2ctl -v`
`Server version: Apache/2.4.7 (Ubuntu)`
`Server built:   Jan 14 2016 17:45:23`

the one who solved it with proxypass used **10 hours** as socket timeout, I think this
is too much or not? I've used now 300 seconds. 

I've added the  proxy timeout settings in my apache config beside the ssl
stuff it looks now as follows:

```
SSLProxyEngine On
ProxyVia On
ProxyPreserveHost On
RequestHeader set X-Forwarded-Proto 'https' env=HTTPS
RequestHeader set X-Forwarded-Port "443"

<Location />
    require all granted
    ProxyPass http://127.0.0.1:8480/ connectiontimeout=5 timeout=300
    ProxyPassReverse /
</Location>

<Location /ws>
    ProxyPass ws://127.0.0.1:8480/ws connectiontimeout=5 timeout=300
</Location>
```

I will try it with the new settings and update this topic, 
Thanks and kind regards

**Comment by ravermeister** [comment]
Update: the changes had no effect :(

**Comment by leonklingele** [comment]
@ravermeister Any news on this?

**Comment by longsleep** [comment]
Closing due to lack of further information/feedback.
