### ISSUE TITLE
Upgrade to oc 9.0.3

### ISSUE THREAD

**Issue by WaaromZoMoeilijk** [strukturag/nextcloud-spreedme#17]
Hey thanks for the amazing app!!

Few days back I've upgraded to OC 9.0.3, every app got disabled. When enabling spreedme it gave me the white screen that it wasn't setup yet, which it was... ran great before.

Now I saw that the config.php and Owncloud.js got overwritten, or a whole new spreeme folder, could also be the case, don't know why but the original files where gone.

After setting it back up, i get a white screen with a error 500

Oc logs show:

```
Error   PHP require_once(): Failed opening required '/var/www/owncloud/apps/spreedme/config/config.php' (include_path='/var/www/owncloud/3rdparty/pear/console_getopt:/var/www/owncloud/3rdparty/pear/pear_exception:/var/www/owncloud/3rdparty/pear/pear-core-minimal/src:/var/www/owncloud/3rdparty/pear/archive_tar:/var/www/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/owncloud/lib/private:/var/www/owncloud/config:/var/www/owncloud/3rdparty:/var/www/owncloud/apps:.:/usr/share/php:/var/www/owncloud') at /var/www/owncloud/lib/autoloader.php#183   3 minutes ago
Error   PHP require_once(/var/www/owncloud/apps/spreedme/config/config.php): failed to open stream: Permission denied at /var/www/owncloud/lib/autoloader.php#183
```

Would this be a core bug?

ps: debug console gives me nothing.

Thank you again

**Comment by leonklingele** [comment]
Hi Ezra,

the upgrade process – when performed automatically by ownCloud – is currently broken.
On system upgrade, ownCloud deletes the whole `spreedme` app directory (including the current configuration files), and replaces it with a new version of the app.

Regarding your error message:
It looks like the file `/var/www/owncloud/apps/spreedme/config/config.php` has the wrong file permissions set, i.e. the PHP process cannot access it.
Can you please check the current permissions of it?

**Comment by WaaromZoMoeilijk** [comment]
That clarifys a lot! Thanks.

Turns out my cronjob to the hourly script that sets permissions had the
wrong path... fixed the path and issue is resolves, thank you!

Great app, thanks again. Also is there any chance that the screen sharing
would get a remote desktop function like team viewer for example, in the
future?

Kind regards,

Ezra

Op di 10 mei 2016 12:02 schreef leonklingele notifications@github.com:

> Hi Ezra,
> 
> the upgrade process – when performed automatically by ownCloud – is
> currently broken.
> On system upgrade, ownCloud deletes the whole `spreedme` app directory
> (including the current configuration files), and replaces it with a new
> version of the app.
> 
> Regarding your error message:
> It looks like the file `/var/www/owncloud/apps/spreedme/config/config.php`
> has the wrong file permissions set, i.e. the PHP process cannot access it.
> Can you please check the current permissions of it?
