### ISSUE TITLE
Keep getting "Please sign in to create rooms"

### ISSUE THREAD

**Issue by gonetil** [strukturag/nextcloud-spreedme#18]
I am having a similar situation than introduced in [issue 8](https://github.com/strukturag/owncloud-spreedme/issues/8), but in my case, my Spreed server is running on a different server than my Owncloud instance.

When I go to Spreed app in owncloud, I get the "please sign in to create rooms" hint. As I understand, this happens because Owncloud is not sharing his users with Spreed, I am right?

In webrtc.conf, I have configured:

```
[http] 
listen = http://my-spreed-server.com:8080
; basePath stays commented
[app]
authorizeRoomJoin = true
authorizeRoomCreation = true  ===> I have also tried false, no change at all
; extra is commented, I am not sure if it should be, but if a put a system path here, Spreed service won't start
plugin = apps/spreedme/extra/static/owncloud.js  ===> I have also tried extra/static/owncloud.js, no change

[users]
enabled = true
mode = sharedsecret
sharedsecret_secret =  f8d091c3d83........ => 64 bit random hex
allowRegistration = true   ==> I have also tried false, but nothing changes.

```

In my Owncloud config, I have:
File **apps/spreedme/config/config.php**:

```
const SPREED_WEBRTC_ORIGIN = 'http://my-spreed-server.com:8080'
const SPREED_WEBRTC_BASEPATH = '';
const SPREED_WEBRTC_SHAREDSECRET = 'f8d091c3d83...." ==> same 64 bit random hex than sharedsecret_secret
const OWNCLOUD_TEMPORARY_PASSWORD_LOGIN_ENABLED  = true  ==> tried false, nothing
const OWNCLOUD_TEMPORARY_PASSWORD_SIGNING_KEY = 'f20e1b84...'
```

File **apps/spreedme/extra/static/config/OwnCloudConfig.js**
`OWNCLOUD_ORIGIN: 'http://my-owncloud-url.com'`

Could you tell me what am I doing wrong?
In case it helps, I am using:
Spreed WebRTC under Ubuntu 14.04
Owncloud 8.2.2 under Debian 7

Thanks a lot for any help!

**Comment by leonklingele** [comment]
Hi Gonzalo,

well, the reason spreed-webrtc is no longer starting if you enable the `extra` field in the `[app]` section is that it can’t find the `spreedme/extra` folder.
Having an enabled `extra` field however is mandatory for the app to work.

As you run spreed-webrtc and ownCloud on two different servers, I suggest to copy the `spreedme/extra` folder from the ownCloud server to the spreed-webrtc server and reference this copied folder in the server.conf accordingly.
Make sure these two folders always stay in sync, as they are required to exist on both servers.

**Comment by gonetil** [comment]
Great, that was it. It works perfect now. Thanks a lot @leonklingele

**Comment by julio1501** [comment]
i have the similar situation as gonetil. But i cannot get the displayname of the authenticeted owncloud user. spreedme is still showing "Me". The debug output shows: "Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://spreedme.domain.com') does not match the recipient window's origin ('https://owncloud.domain.com').
Thanks for any help

**Comment by leonklingele** [comment]
Hi @julio1501,

can you please post your config files / describe your setup?

**Comment by julio1501** [comment]
I´m using Spreed WebRTC under Debian 8
Owncloud 8.2.5 under Debian 8 (with user_ldap App)
package: https://github.com/strukturag/spreed-webrtc.git 

**Server.conf**
[http] 
listen = webrtc.mydomain.de:8080
; basePath 
[https]
listen = webrtc.mydomain.de:8443
certificate = /etc/ssl/certs/certificate.crt
key = /etc/ssl/private/mykey.key
[app]
authorizeRoomJoin = true
authorizeRoomCreation = true  
extra = /var/nodes/spreed-webrtc/extra
plugin = extra/static/owncloud.js

[users]
enabled = true
mode = sharedsecret
sharedsecret_secret =  123456789fgfgfgg etc....

[modules]
screensharing = true
youtube = true
presentation = true
contacts = true

**OwnCloudConfig.js**
OWNCLOUD_ORIGIN: 'https://owncloud.mydomain.de/subfolder'

**config.php**
const SPREED_WEBRTC_ORIGIN = 'https://webrtc.mydomain.de:8080';

**Comment by leonklingele** [comment]
Hi @julio1501,

you should use `const SPREED_WEBRTC_ORIGIN = 'https://webrtc.mydomain.de:8443';` in config.php.
Other than that you will not be able to use the Screensharing feature, as spreed-webrtc and ownCloud run on two different hosts (https://webrtc.mydomain.de:8443 and https://owncloud.mydomain.de).

If you want to use Screensharing, simply set up your web server (most likely nginx or Apache) to act as a reverse proxy for spreed-webrtc.
With a reverse proxy, you can make spreed-webrtc available at e.g. https://owncloud.mydomain.de/webrtc, thus on the same host as your ownCloud instance.
See https://github.com/strukturag/nextcloud-spreedme/blob/master/doc/example-config-nginx.txt (nginx) and https://github.com/strukturag/spreed-webrtc/blob/master/doc/APACHE.txt (Apache) as example configurations.

**Comment by julio1501** [comment]
Hi @leonklingele ,
thanks I will try this.
