### ISSUE TITLE
Allow calls with external persons

### ISSUE THREAD

**Issue by LukasReschke** [strukturag/nextcloud-spreedme#2]
It would probably make sense to offer a possibility to start a call with an external person that does not have an ownCloud account. Something like: "Create conference link" that can then be shared with external persons.

**Comment by leonklingele** [comment]
Yup, already working on it. Branch will be pushed this or next week.
Stay tuned!

EDIT:
Decided to push it now. Will merge next week.
https://github.com/strukturag/owncloud-spreedme/commits/temporary-password

**Comment by LukasReschke** [comment]
:rocket: :smile:

**Comment by leonklingele** [comment]
This reference was not intended. I'm sorry.

**Comment by leonklingele** [comment]
Merged into master.
