### ISSUE TITLE
an error occured retry

### ISSUE THREAD

**Issue by Jetneg974** [strukturag/nextcloud-spreedme#20]
Hi all,

I'installed spreedme no erreur

Spreed.ME Version 0.1.6

Ran test #1 (testOwncloudPhpConfigFile):
Passed without an error

Ran test #2 (testOwncloudJavascriptConfigFile):
Passed without an error

Ran test #3 (testSpreedWebRTCAPI):
Passed without an error

Passed all tests. Everything seems to be set up correctly! :)

But when i connect me on the application, i've the screen with all option but i've the message An error occured " Retry"

Could you help me please ?

Cheers,

**Comment by leonklingele** [comment]
Hi Jetneg974,

can you please check your browser's developer console for any errors?
1. Open the Spreed.ME app in ownCloud
2. Append ?debug to the URL, i.e. https://domain.com/index.php/apps/spreedme/?debug
3. Right click on the ownCloud site
4. Click "Inspect element" (very bottom)
5. Check what it says in the console and paste it here

Thank you :)

**Comment by Jetneg974** [comment]
Hi leonklingele,

When i open my url with /?dedug, i have nothing, it's the same page  

When i Inspect with the console 

Launching ...
main.js:45 Web fonts loaded.
app.js:231 Selected language: en
main.js:45 Bootstrapping ...
app.js:221 App runtime id: uy7xu77
app.js:220 Service version: 0.24.12-1~trusty1
app.js:220 Ws URL: wss://myurl/webrtc/ws
app.js:220 Secure Contextual Escaping: true
app.js:231 Initializing ...
PostMessageAPI.js:50 PostMessageAPI: POSTING FROM Location TO https://myurl Object
app.js:223 Screensharing support true autoinstall
main.js:39 The <keygen> element is deprecated and will be removed in M54, around October 2016. See https://www.chromestatus.com/features/5716060992962560 for more details.
app.js:221 Initial room path set, continuing to connect ...
app.js:221 Ready to connect ...
app.js:225 Checking for media access ...
app.js:225 Continue with connect after media check ...
app.js:231 Initializing complete.
app.js:221 Connecting ...
PostMessageAPI.js:50 PostMessageAPI: Got event MessageEvent
app.js:219 WebSocket connection to 'wss://myurl/webrtc/ws' failed: Error during WebSocket handshake: Unexpected response code: 500
app.js:219 Connector on connection error.
PostMessageAPI.js:50 PostMessageAPI: Got event MessageEvent
PostMessageAPI.js:50 PostMessageAPI: Got event MessageEvent
app.js:222 Created new video layout renderer invisible n

i have one erreur and two warnings

the warning 

the first 

The <keygen> element is deprecated and will be removed in M54, around October 2016. See https://www.chromestatus.com/features/5716060992962560 for more details.

the second

Connector on connection error.

the error 

WebSocket connection to 'wss://myurl/webrtc/ws' failed: Error during WebSocket handshake: Unexpected response code: 500

Cheers, :)

**Comment by leonklingele** [comment]
@Jetneg974 This looks like an issue with your webserver configuration.
Can you please create a pastie with your nginx / Apache config at https://pastebin.ubuntu.com ?

Have you checked the logs of spreed-webrtc?

**Comment by Jetneg974** [comment]
@leonklingele  I use only apache2, when i open my file error.log i've 

```
[Thu Jun 09 11:52:55.768915 2016] [mpm_prefork:notice] [pid 9791] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.16 OpenSSL/1.0.1f configured -- resuming normal operations
[Thu Jun 09 11:52:55.768942 2016] [core:notice] [pid 9791] AH00094: Command line: '/usr/sbin/apache2'
```

When i open the log webrtc i've 

```
server 2016/06/09 11:16:18 Starting HTTP server on 127.0.0.1:8080
server 2016/06/09 11:52:27 Got signal 15, stopping all services
server 2016/06/09 11:52:27 Stopped HTTP server on 127.0.0.1:8080
server 2016/06/09 11:52:27 Using '/webrtc/' base base path.
server 2016/06/09 11:52:27.487165 Enabled modules: [contacts screensharing youtube presentation]
server 2016/06/09 11:52:27.487805 Loaded extra templates from: /var/www/owncloud/apps/spreedme/extra
server 2016/06/09 11:52:27.487817 Using the number of CPU's (1) as GOMAXPROCS
server 2016/06/09 11:52:27.487821 Max open files are 1024
server 2016/06/09 11:52:27.489050 Added URL handler /extra/static/... for static files in /var/www/owncloud/apps/spreedme/extra/static/...
server 2016/06/09 11:52:27 Starting HTTP server on 127.0.0.1:8080
```

My conf apache is 

```
<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
</VirtualHost>

<Location /webrtc/>
ProxyPass http://127.0.0.1:8080/webrtc/
ProxyPassReverse /
</Location>

<Location /webrtc/ws>
ProxyPass ws://127.0.0.1:8080/webrtc/ws
</Location>
ProxyVia On
ProxyPreserveHost On
RequestHeader set X-Forwarded-Proto 'https' env=HTTPS

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

My conf is on the path /etc/apache2/sites-enable/000-default.conf 

Cheers,

**Comment by longsleep** [comment]
Well, that error 500 of yours must be logged somewhere. You need to find it so we could figure out what is going wrong. Also the the access log and make sure you see the 500 reply there. If not, then the request never even reaches that server.

**Comment by Jetneg974** [comment]
@longsleep in acces.log on apache2 i've  that
::1 - - [09/Jun/2016:15:32:35 +0200] "OPTIONS \* HTTP/1.0" 200 125 "-" "Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.16 OpenSSL/1.0.1f (internal dummy connection)"

Cheers

**Comment by longsleep** [comment]
Wel well that is not the error. If you see OPTIONS requests it usually means something is doing cross domain requests (which might be one of the issues here). The error above you see must show as something like "GET 500" in your access log and with the IP address of your client.

**Comment by Jetneg974** [comment]
@longsleep do you know where i can find this information ?

**Comment by Jetneg974** [comment]
because in the file other_vhosts_acces i'have my ip and  [09/Jun/2016:10:59:17 +0200] "GET /index.php/apps/spreedme/ HTTP/1.1" 302 599 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"

**Comment by longsleep** [comment]
No clue, its your Apache configuration after all. Your other log file shows a redirect (302) also unrelated. You are earchfing for the error you got "'wss://myurl/webrtc/ws' failed: Error during WebSocket handshake: Unexpected response code: 500" , means something like "GET /webrtc/ws HTTP/1.1" 500 line. If you found this then check the corresponding error log for the 500 error description. Without at we can only guess.

**Comment by Jetneg974** [comment]
@longsleep i've this error on my syslog

AH01144: No protocol handler was valid for the URL /webrtc/ws. If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule

"GET /webrtc/ws HTTP/1.1" 500 1003 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"

cheers

**Comment by Jetneg974** [comment]
@longsleep but 

root@owncloud:/etc/apache2/sites-enabled# a2enmod proxy_http
Considering dependency proxy for proxy_http:
Module proxy already enabled
Module proxy_http already enabled
root@owncloud:/etc/apache2/sites-enabled# a2enmod proxy
Module proxy already enabled
root@owncloud:/etc/apache2/sites-enabled#

**Comment by longsleep** [comment]
Yes that is the correct error. It means you Apache is lacking websocket proxy support. I am pretty sure it's mentioned in the docs for the owncloud plugin. Please check.

**Comment by Jetneg974** [comment]
it's done cheers,
