### ISSUE TITLE
Installing and configuring Restund - STUN

### ISSUE THREAD

**Issue by Jetneg974** [strukturag/nextcloud-spreedme#21]
Hi all,

I've juste one question, it's possible install stun on the same server Owncloud ?

Cheers,

**Comment by longsleep** [comment]
Sure you can install any stun server anywhere. Though if it makes sense depends on network setup. If you think about setting up a STUN server, i suggest you follow https://github.com/spreedbox/spreedbox/wiki/Use-TURN-server (just disable TURN if do not need it).
