### ISSUE TITLE
No one else here!

### ISSUE THREAD

**Issue by erikkn** [strukturag/nextcloud-spreedme#22]
Guys,

I added the PPA and installed webrtc (https://github.com/strukturag/spreed-webrtc/wiki/Ubuntu-Repository) . After this I configured /etc/spreed/webrtc.conf as described here: https://github.com/strukturag/owncloud-spreedme/blob/master/README.md 
After I enabled the app in OC I could open the app, but I only see 'No one else here!' .

Please help!

**Comment by leonklingele** [comment]
Hi Erik,

have you checked that you and the other participant(s) are in the same room?

Also please verify that the `/index.php/apps/spreedme/admin/debug` endpoint says 'Everything seems to be set up correctly'.
If not, take a look at your browser's developer console and post error messages (if any):
1. Open the Spreed.ME app in ownCloud
2. Append ?debug to the URL, i.e. https://domain.com/index.php/apps/spreedme/?debug
3. Right click on the ownCloud site
4. Click "Inspect element" (very bottom)
5. Check what it says in the console and paste it here

**Comment by erikkn** [comment]
Hi @leonklingele  , thanks for your reply

**Output of http://domainname/apps/spreedme/admin/debug:**

Spreed.ME Version 0.1.6
Ran test #1 (testOwncloudPhpConfigFile):
   Passed without an error
Ran test #2 (testOwncloudJavascriptConfigFile):
   Passed without an error
Ran test #3 (testSpreedWebRTCAPI):
   Passed without an error
Passed all tests. Everything seems to be set up correctly! :) 

**Console output, I apologize for the large output ;-) :**

Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead. (unknown)
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src http://MYDOMAINNAME.nl 'unsafe-eval'"). spreedme
Launching ... main.js:45:15198
Web fonts loaded. main.js:45:14339
Browser support for filesystem API not found. app.js:222:3612
Selected language: en app.js:231:16308
Bootstrapping ... main.js:45:15107
App runtime id: ql69fkq app.js:221:3272
Service version: 0.24.12-1~trusty1 app.js:220:31202
"Ws URL: ws://chat.MYDOMAINNAME.nl:8080/webrtc/ws" app.js:220:31237
Secure Contextual Escaping: true app.js:220:31263
Initializing ... app.js:231:15115
'mozHidden' and 'mozVisibilityState' are deprecated.  Please use the unprefixed 'hidden' and 'visibilityState' instead. base.js:260:13747
PostMessageAPI: POSTING FROM Location → http://chat.MYDOMAINNAME.nl:8080/webrtc/ "TO http://chat.MYDOMAINNAME.nl:8080" Object { type: "init" } PostMessageAPI.js:50:3
Screensharing support false  app.js:223:2622
Browser support for binary file transfers not found. app.js:222:9987
Initial room path set, continuing to connect ... app.js:221:1764
Ready to connect ... app.js:221:1568
Checking for media access ... app.js:225:13936
Continue with connect after media check ... app.js:225:13566
Initializing complete. app.js:231:15194
Connecting ... app.js:221:1298
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://chat.MYDOMAINNAME.nl:8080') does not match the recipient window's origin ('http://cloud.MYDOMAINNAME.nl'). webrtc
Created new video layout renderer invisible Object {  } app.js:222:19120
Connector on connection open. app.js:219:1125
OC: selfReceived Object { Type: "Self", Id: "MTQ2Njc2ODIxOHxmVE1XOWtBTDJMa00xSTJ…", Sid: "Sut5GCOCtqEe4bgUUGzyc16i3QGyixUm", Userid: "", Suserid: "", Token: "MTQ2Njc2ODIxOHxEdURRbngyZ2JNSklZRkp…", Version: "0.24.12-1~trusty1", ApiVersion: 1.4, Turn: Object, Stun: Array[0] } owncloud.js:64:3
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:5:17117
Connector on connection close. close { target: WebSocket, isTrusted: true, wasClean: true, code: 1005, reason: "", eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1466768241330933, originalTarget: WebSocket } false app.js:219:1657
Stored data at the resurrection shrine Object { status: "waiting", id: "MTQ2Njc2ODIxOHxmVE1XOWtBTDJMa00xSTJ…" } app.js:227:23860
Requesting to reconnect ... app.js:227:24141
Reconnecting ... app.js:221:1405
Connector on connection open. app.js:219:1125
OC: selfReceived Object { Type: "Self", Id: "MTQ2Njc2ODIxOHxmVE1XOWtBTDJMa00xSTJ…", Sid: "Sut5GCOCtqEe4bgUUGzyc16i3QGyixUm", Userid: "", Suserid: "", Token: "MTQ2Njc2ODI0M3x5Mm5GOVFDMWRIZDFyeEF…", Version: "0.24.12-1~trusty1", ApiVersion: 1.4, Turn: Object, Stun: Array[0] } owncloud.js:64:3
Using resurrection shrine Object { status: "waiting", id: "MTQ2Njc2ODIxOHxmVE1XOWtBTDJMa00xSTJ…" } app.js:227:21989
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. webrtc
Connector on connection close. close { target: WebSocket, isTrusted: true, wasClean: true, code: 1005, reason: "", eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1466768297394141, originalTarget: WebSocket } false app.js:219:1657
Stored data at the resurrection shrine Object { status: "waiting", id: "MTQ2Njc2ODIxOHxmVE1XOWtBTDJMa00xSTJ…" } app.js:227:23860
Requesting to reconnect ... app.js:227:24141
Reconnecting ... app.js:221:1405
Connector on connection open. app.js:219:1125
OC: selfReceived Object { Type: "Self", Id: "MTQ2Njc2ODIxOHxmVE1XOWtBTDJMa00xSTJ…", Sid: "Sut5GCOCtqEe4bgUUGzyc16i3QGyixUm", Userid: "", Suserid: "", Token: "MTQ2Njc2ODI5OXxLeGphX3p0MjUtTUNOakl…", Version: "0.24.12-1~trusty1", ApiVersion: 1.4, Turn: Object, Stun: Array[0] } owncloud.js:64:3
Using resurrection shrine Object { status: "waiting", id: "MTQ2Njc2ODIxOHxmVE1XOWtBTDJMa00xSTJ…" }

**Comment by leonklingele** [comment]
Sorry, please _also_ post the dev console output.

**Comment by erikkn** [comment]
What do you mean with the dev console? You mean the /var/log/spreed/webrtc/server.log ?

**Comment by leonklingele** [comment]
It looks like something is not configured correctly.

```
PostMessageAPI: POSTING FROM Location → http://chat.MYDOMAINNAME.nl:8080/webrtc/ "TO http://chat.MYDOMAINNAME.nl:8080"
```

vs.

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://chat.MYDOMAINNAME.nl:8080') does not match the recipient window's origin ('http://cloud.MYDOMAINNAME.nl').
```

Can you please describe your setup and post the config files to https://paste.ubuntu.com/?
- Does your ownCloud run on `http://chat.MYDOMAINNAME.nl:8080` or `http://cloud.MYDOMAINNAME.nl`?

**Comment by erikkn** [comment]
Config files:
https://paste.ubuntu.com/17797915/
https://paste.ubuntu.com/17797976/
https://paste.ubuntu.com/17797991/

Spreedme is installed as package. Config file path: /etc/spreed/webrtc.conf. Spreedme and OC are installed on the same server.

**Comment by leonklingele** [comment]
First off: spreed-webrtc and ownCloud both need to be available via https, otherwise you will not be able to use the audio- and video conferencing feature.
1. `OWNCLOUD_ORIGIN` in the .js config file must point to the ownCloud host, most likely `https://cloud.MYDOMAINNAME.nl`
2. `SPREED_WEBRTC_ORIGIN` in the .php config file must point to the spreed-webrtc host. As you said both oC and spreed-webrtc run on the same machine, it should point to the same host as `OWNCLOUD_ORIGIN` from step `1.`
3. `listen = chat.zuydonline.nl:8080` from the .conf file should be changed back to `listen = 127.0.0.1:8080`. Please set up your nginx / Apache as a reverse proxy as explained here: https://github.com/strukturag/spreed-webrtc/blob/master/doc/NGINX.txt / https://github.com/strukturag/spreed-webrtc/blob/master/doc/APACHE.txt

Also please make sure to change your secrets, as you have included them in your pasties 🙀

**Comment by erikkn** [comment]
About the audio- and video conferencing (https): thanks for the info, i'll setup https right away.

I just changed the /var/www/owncloud/apps/spreedme/extra/static/config/OwnCloudConfig.js and the /var/www/owncloud/apps/spreedme/config/config.php file like you said. I changed them both to: cloud.DOMAINNAME.nl:8080.
When I change the listen statement in /etc/spreed/webrct.conf in '127.0.0.1:8080' the spreedme OC app gives a timeout, the app can't reach the server. If i change it to 'cloud.DOMAINNAME.nl' and edit my /etc/hosts file, the app is working again, but still giving the 'No one else here' .

I am using nginx, but do I really need to setup a reverse proxy for it to work?

**Comment by leonklingele** [comment]
Yes, it is recommended to access both spreed-webrtc and oC on port 443. Thus, a reverse proxy is required.
Just take a look at our example config. Just copy&paste the `location /webrtc` and `map $http_upgrade $connection_upgrade` block to your oC virtual server and reload nginx.

**Comment by longsleep** [comment]
Note that is essentially useless to run Spreed WebRTC without HTTPS, as for user media access, encryption is mandatory since Chrome 47 (with localhost exception).

**Comment by erikkn** [comment]
Hi guys,

I just reinstalled my VM but with the same webrtc/OC app config, except for the http section. The webrtc server is now using https, and it's possible to open the OC app :). I also configured /etc/nginx/nginx.conf with the map $http_upgrade $connection_upgrade and the proxy settings. The location directive is placed in my virtualhost file /etc/nginx/sites-available/owncloud . After a nginx reload and disable-> enable of the spreedme app, I still can't see other users.  

**The inspect element - console method gives the following output:**
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://cloud.zDOMAINNAME.nl:8443') does not match the recipient window's origin ('https://cloud.DOMAINNAME.nl').

P.S. I still have the 'root' and the 'basePath' parameters in the http section enabled, otherwise the app is not working

**Comment by leonklingele** [comment]
If you use nginx as a reverse proxy and configured it so spreed-webrtc and oC are both available at `cloud.DOMAINNAME.nl:443`, you should update the Spreed.ME oC config files accordingly.
They should not use/mention port 8443.

**Comment by erikkn** [comment]
@leonklingele I'm sorry, but I'm kinda new with reverse proxies. Could you please verify that my nginx configuration is correct?
/etc/nginx/sites-available/owncloud (VirtualHost): https://paste.ubuntu.com/17849070/
/etc/nginx/nginx.conf: https://paste.ubuntu.com/17849120/

**Comment by leonklingele** [comment]
Hi @erikkn 

don't modify `nginx.conf`. Revert it to your previous configuration.
`/etc/nginx/sites-available/owncloud` should look like this:

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

upstream php-handler {
    server PHP_CONFIG;
}

server {
    listen 443 ssl;
    server_name DOMAINNAME.nl;

    ... The stuff you already have here remains

    location /webrtc {
        proxy_pass http://localhost:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_buffering             on;
        proxy_ignore_client_abort   off;
        proxy_redirect              off;
        proxy_connect_timeout       90;
        proxy_send_timeout          90;
        proxy_read_timeout          90;
        proxy_buffer_size           4k;
        proxy_buffers               4 32k;
        proxy_busy_buffers_size     64k;
        proxy_temp_file_write_size  64k;
        proxy_next_upstream         error timeout invalid_header http_502 http_503 http_504;
    }

}

```

**Comment by erikkn** [comment]
Thanks, that helped me a lot. Unfortunately I still encounter some problems.
- I've edited my /etc/nginx/sites-available/owncloud file like you said, but changed the proxy_pass statement to: https://cloud.DOMAINNAME.nl:8443
- My /etc/spreed/webrtc.conf is listening on: cloud.DOMAINNAME.nl:8443 . 
- The ../spreedme/extra/config/config.php -> SPREED_WEBRTC_ORIGIN statement is listening on 'https://cloud.DOMAINNAME.nl' .
- The ../spreedme/extra/static/config/OwnCloudConfig.js -> OWNCLOUD_ORIGIN statement is clear/empty . 

When I restart all services and disable-enable the spreedme OC app again, I get a white page. My Nginx error.log file says:  
*3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.60.80, server: cloud.DOMAINNAME.nl, request: "GET /webrtc/ HTTP/1.1", upstream: "https://192.168.60.1:8443/webrtc/", host: "cloud.DOMAINNAME.nl"

**Comment by leonklingele** [comment]
It's perfectly fine to let spreed-webrtc listen on port 8080.
Do not modify the `listen = 127.0.0.1:8080` in `webrtc.conf`.
Do not modify the `proxy_pass http://localhost:8080;` in `/etc/nginx/sites-available/owncloud`.

The reverse proxy functions like this:
Request to https://cloud.domainname/webrtc/ --> nginx (reverse proxy) --> spreed-webrtc on port 8080

**Comment by erikkn** [comment]
@leonklingele , thanks for your help, but I still get the white page page and the same Nginx error in my log file.
I don't want to be a annoying, but maybe you could check my configuration for the last time?

/etc/nginx/sites-available/owncloud : https://paste.ubuntu.com/17907188/
/etc/spreed/webrtc.conf: https://paste.ubuntu.com/17907248/
../apps/spreedme/config/config.php: https://paste.ubuntu.com/17907306/
../apps/spreedme/extra/static/config/OwnCloudConfig.js: https://paste.ubuntu.com/17907340/

**Comment by leonklingele** [comment]
Everything looks fine except `config.php`.
Please try `const SPREED_WEBRTC_ORIGIN = '';` (empty string)

**Comment by erikkn** [comment]
Nope, unfortunately that didn't fix it, result: (check picture)
![screenshot from 2016-06-26 16 37 53](https://cloud.githubusercontent.com/assets/19726317/16362981/de312e78-3bbc-11e6-9744-9c1e84851b9d.png)

We're both out of option :(?

**Comment by leonklingele** [comment]
Please take a look at the developer console to see what exactly doesn't work (and why).

**Comment by erikkn** [comment]
I expect you mean the inspect element - console button? Result:

Refused to execute script from 'https://cloud.DOMAINNAME.nl/webrtc/static/ver=02412-1~trusty1/js/libs/require/require.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by leonklingele** [comment]
Now the problem is that the `location ~* \.(?:css|js)$` block in your ownCloud nginx config has a higher priority than the `location /webrtc` block.
Please change it to `location ^~ /webrtc`.

**Comment by erikkn** [comment]
Ooooh myyyy.... @leonklingele you're just awesome! It works, I changed my virtual host to: location ^~/webrtc { and it's working!! Now I can see people, chat with them and have video conferences.

Thank you so much, you're the hero of the day ;-)

**Comment by leonklingele** [comment]
🎉 🐳 🎈

**Comment by kbaegis** [comment]
Also getting "No one else here" after following setup guide. A check for this would be really helpful. 
<img width="241" alt="screen shot 2016-08-04 at 5 28 02 am" src="https://cloud.githubusercontent.com/assets/306920/17400306/58d5e9a6-5a04-11e6-8b93-e6bdc889ddb8.png">
<img width="255" alt="screen shot 2016-08-04 at 5 07 04 am" src="https://cloud.githubusercontent.com/assets/306920/17400305/58d5b2e2-5a04-11e6-8d81-bf384d6036e7.png">
