### ISSUE TITLE
installation in ubuntu 64 bits - what missed

### ISSUE THREAD

**Issue by johnfelipe** [strukturag/nextcloud-spreedme#24]
This is my steps for install and integrate with `spreed-webrtc`

```
sudo apt-get install php5 php5-fpm php5-cli php5-curl
sudo service php5-fpm restart

git clone https://github.com/strukturag/owncloud-spreedme.git
cd owncloud-spreedme/

mkdir /home/felipe/spreed-webrtc/extra.d

ln -sf /home/felipe/owncloud-spreedme/extra /home/felipe/spreed-webrtc/extra.d/spreedme

sudo nano /home/felipe/spreed-webrtc/server.conf

##
;authorizeRoomJoin = false
To
authorizeRoomJoin = true

Add in (app section)
extra.d = /home/felipe/spreed-webrtc/extra.d

enabled = false
To
enabled = true

;mode = sharedsecret
To
mode = sharedsecret

;sharedsecret_secret = some-secret-do-not-keep
To
sharedsecret_secret = 037a21f6c779f73c1c546b02ca33cf9cdf6cd83959d845dcab6997e06e67acee

##

cp /home/felipe/owncloud-spreedme/config/config.php.in /home/felipe/owncloud-spreedme/config/config.php

sudo nano /home/felipe/owncloud-spreedme/config/config.php

##
    const SPREED_WEBRTC_ORIGIN = 'http://sesionentiemporeal.felipeurrego.com:8080';

    const SPREED_WEBRTC_SHAREDSECRET = '037a21f6c779f73c1c546b02ca33cf9cdf6cd83959d845dcab6997e06e67acee';
##

cp /home/felipe/owncloud-spreedme/extra/static/config/OwnCloudConfig.js.in /home/felipe/owncloud-spreedme/extra/static/config/OwnCloudConfig.js

sudo nano /home/felipe/owncloud-spreedme/extra/static/config/OwnCloudConfig.js

##
            OWNCLOUD_ORIGIN: 'http://sesionentiemporeal.felipeurrego.com:2017',
##

sudo apt-get install -y nginx
sudo rm /etc/nginx/sites-enabled/default
sudo nano /etc/nginx/sites-available/spreed

#####
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

upstream php-fpm-handler {
    server unix:/var/run/php5-fpm.sock;
}

server {

    listen 2017 default_server;

    server_name 127.0.0.1 sesionentiemporeal.felipeurrego.com;

    root /home/felipe/owncloud-spreedme;

    # ownCloud blocks
    location / {
        try_files $uri $uri/ /index.php;
    }
    location ~ \.php(?:$|/) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS on;
        fastcgi_param modHeadersAvailable true; # Avoid sending the security headers twice
        fastcgi_pass php-fpm-handler;
        fastcgi_intercept_errors on;
    }

    # spreed-webrtc blocks
    location /webrtc {
        proxy_pass http://localhost:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_buffering             on;
        proxy_ignore_client_abort   off;
        proxy_redirect              off;
        proxy_connect_timeout       90;
        proxy_send_timeout          90;
        proxy_read_timeout          90;
        proxy_buffer_size           4k;
        proxy_buffers               4 32k;
        proxy_busy_buffers_size     64k;
        proxy_temp_file_write_size  64k;
        proxy_next_upstream         error timeout invalid_header http_502 http_503 http_504;
    }

}
#####
```

I want in

`http://sesionentiemporeal.felipeurrego.com:2017/` spreedme
`http://sesionentiemporeal.felipeurrego.com:8080/` webrtc

Tnks for any help

**Comment by leonklingele** [comment]
Hi @johnfelipe,

this repository contains a plugin for ownCloud. If you do not have an ownCloud / Nextcloud instance running on your server, make sure to set it up before using this repository's app: https://nextcloud.com/install/#instructions-server
Please note that in order to use spreed-webrtc, you don't have to use ownCloud / Nextcloud / owncloud-spreedme (this repository).

If you want to use this app for ownCloud, here's what's wrong with the steps you posted:
- `owncloud-spreedme` currently only supports the `extra.d` directory of spreed-webrtc in the `develop` branch. Switch to your `owncloud-spreedme` directory and run `git checkout develop`.
- Please don't use the sample nginx configuration. It just gives a rough overview of how your configuration could look like.
- Both ownCloud and spreed-webrtc must run on `https`
- You should prefer to run ownCloud and spreed-webrtc on the same host (e.g. `https://sesionentiemporeal.felipeurrego.com/` (ownCloud), `https://sesionentiemporeal.felipeurrego.com/webrtc` (spreed-webrtc). Update 
- Also don't forget to change your `sharedsecret`. :)

**Comment by johnfelipe** [comment]
for admin panel, or admin user i dont need spreedme?
How can add gruop of users into same room
How can add new contacts?
TNks

**Comment by leonklingele** [comment]
I'm sorry, I don't understand your question.
Please describe what you want to achieve. Do you only want to use spreed-webrtc?

**Comment by johnfelipe** [comment]
spreed-webrtc havent admin UI?

**Comment by leonklingele** [comment]
No, what do you want to administrate?

**Comment by johnfelipe** [comment]
contacts, groups, rooms, etc

**Comment by johnfelipe** [comment]
how can i administrate contacts, groups, rooms, etc???

**Comment by leonklingele** [comment]
Hi @johnfelipe,
I suggest you read through spreed-webrtc's `server.conf` config file. Everything should be explained there – probably better than I could explain it to you.

**Comment by longsleep** [comment]
There is no admin UI. Spreed WebRTC provides a call and conferencing web client with the required apis to extend it with contacts, groups and administration capabilities. Such functions are not part of Spreed WebRTC itself or the owncloud plugin where this tracker belongs to. If you have suggestions what and how the ownCloud plugin should be extended please open up a separate feature request.
