### ISSUE TITLE
Succesfully setup WebRTC / Spreed.me, Videochat impossible

### ISSUE THREAD

**Issue by Op3rat0r** [strukturag/nextcloud-spreedme#27]
I think my WebRTC setup works so far. The server is on my Uberspace ([https://uberspace.de](https://uberspace.de)) installed (running Apache 2.2 [Webserver](https://wiki.uberspace.de/webserver)). The NextCloud is on the same server. A Port for the WebRTC server has been opened in the firewall to the outside.

Now, when I try to make a video Conference from my Workstation and from my Laptop in the same LAN the Video Conference works. But when I try to start a video call from a computer outside of my network it  disconnects after a short time. No picture or sound is built up. Tested with Chrome and Firefox.

```
The source code of the page is shown below. Same in Chrome and Firefox:
        <div id="content-wrapper">
            <div id="content" class="app-spreedme" role="main">

<script id="sharedconfig" type="application/json">{"is_guest":false,"features":{"temporary_password":true}}</script>

<div id="debug"><b>Debug</b><br /></div>

<div id="container">
    <iframe src="https://cloud.zonedata.de:63091/spreed-webrtc/?debug" allowfullscreen></iframe>
</div>
            </div>
        </div>
    </body>
</html>
```

The frame source code in Chrome:

```
<script id="globalcontext" type="application/json">{"App":"main","Cfg":{"Title":"Spreed WebRTC","S":"static/ver=1468103034","B":"/spreed-webrtc/","Token":"a long Token <deleted>","Renegotiation":false,"StunURIs":[],"TurnURIs":[],"Tokens":false,"Version":"unreleased.1468103034","UsersEnabled":true,"UsersAllowRegistration":false,"UsersMode":"sharedsecret","DefaultRoomEnabled":true,"Plugin":"extra/static/owncloud.js","AuthorizeRoomCreation":false,"AuthorizeRoomJoin":true,"Modules":["contacts","screensharing","youtube","presentation"]},"Host":"cloud.zonedata.de:63091","Ssl":true,"Csp":false,"Languages":["de-de","de","en-us","en"],"S":"static/ver=1468103034"}</script>
</head>
<body spreed-webrtc>
<div id="background"></div>
<div id="loader"><div><i class="fa fa-circle-o-notch fa-spin"></i><div class="loader-message"></div></div></div>
<ui></ui>
<script data-main="static/ver=1468103034/js/main" data-plugin="extra/static/owncloud.js" src="static/ver=1468103034/js/libs/require/require.js"></script>
```

[cloud.zonedata.de-1468245171261.log.txt](https://github.com/strukturag/owncloud-spreedme/files/357353/cloud.zonedata.de-1468245171261.log.txt)

I have only very limited access to the mobile network (only EDGE). But I can observe in the Serverlog the following (which is reproducible):

> _Maybe that has to do with the limited access!_
> `@400000005783b156029df1dc server 2016/07/11 16:46:36.043823 http: TLS handshake error from IP-Adress:Port: EOF`

and

`@400000005783b1573265b1fc server 2016/07/11 16:46:37.845356 Error while reading 34 websocket: close 1006 unexpected EOF`

I saw there was already such a [case](https://github.com/strukturag/owncloud-spreedme/issues/16).
But I do not know how I can fix the problem. Should I make changes in the Next Cloud .htaccess file (ProxyTimeout Directive)?

**Comment by longsleep** [comment]
Closed as requested in #25
