### ISSUE TITLE
Contacts not save after logout

### ISSUE THREAD

**Issue by BurtGummer** [strukturag/nextcloud-spreedme#32]
Hello,

I login to nextcloud and change to the spreed.me-App. I add a contact with klicking the star:

![image](https://cloud.githubusercontent.com/assets/1249295/17169492/0670752c-53e8-11e6-817e-44fa2a9d2608.png)

The contact accept my request. Now i have this contact in my contact-list. If i logout and login to nextcloud, there are no contacts in my contact-list:

![image](https://cloud.githubusercontent.com/assets/1249295/17169587/75fc05a0-53e8-11e6-9d67-b0ae286953e6.png)

Maybe a bug?

**Comment by leonklingele** [comment]
Hi @BurtGummer,

this is because contacts are saved on a user-session level in your browser.
As soon as you log out from ownCloud or switch your browser, your contacts are "lost".

We are working on an integration with the NC/oC contacts so your contacts will remain, even if you log in from another browser / log out then log back in again.

See https://github.com/strukturag/nextcloud-spreedme/issues/14

**Comment by longsleep** [comment]
Well if you sign-in again with the same browser the contacts should be there again, unless the local storage data was removed. There are addons preventing persistent storage - make sure you do not have such an addon enabled.

**Comment by leonklingele** [comment]
Hi @BurtGummer,

were you able to find out why your Contacts got deleted after logging out?

**Comment by BurtGummer** [comment]
I have try it with different windows 7 machines, with different browsers (chrome, firefox, vivaldi), but the contacts always lost. there are no addons like "History Wipe" or else installed. I cant say much more.. sorry :/

**Comment by leonklingele** [comment]
Hi @BurtGummer,

I tried to reproduce the issue:
1. Open Spreed.ME app in both Chrome and Firefox with a different oC login
2. Add other participant as a contact
3. Log out from oC in Chrome
4. Login again
5. Open Spreed.ME app
6. Contact still there

Can you please try to follow these steps?
Did you do something differently?

Also please check the Local Storage of your browser.
Here’s how to access it (in Chrome):
1. Right-click on the Spreed.ME app webpage
2. Click "Inspect Element" (very bottom)
3. Open the "Resources" panel
4. Expand "Local Storage" (on the left)
5. Click on your host

What do you see there? Does anything change after logging out / back in again?

**Comment by BurtGummer** [comment]
I try it again, now it works. I think, because we test with many different PC's, everytime we use a new browser - thats the problem. We think its saved in the user-settings on the server, not in the browser.
Sorry and thanks for your time and work!
