### ISSUE TITLE
owncloud.js has to be renamed

### ISSUE THREAD

**Issue by JSoko** [strukturag/nextcloud-spreedme#33]
Installed nextcloud-spreed on my nextcloud installation.

Spreed shows me "Failed to load app!"

Had to rename :/var/www/owncloud/apps/spreedme/extra/static/owncloud.js to nextcloud.js 

Than it worked...
![spreed_failed](https://cloud.githubusercontent.com/assets/5583290/17202728/45a4323e-549b-11e6-9c5d-d8c751b660bd.jpg)
![404](https://cloud.githubusercontent.com/assets/5583290/17202742/6fa77afa-549b-11e6-9432-c1d9b48275fe.jpg)

**Comment by longsleep** [comment]
Thanks for your report. The documentation in master was wrong as the file is indeed still named `owncloud.js`. So you should not rename the file but rather use `plugin = extra/static/owncloud.js` in the configuration.

**Comment by WaaromZoMoeilijk** [comment]
I should just add another line, a second one in the webrtc.conf then right?
