### ISSUE TITLE
Configuration files lost on web upgrade

### ISSUE THREAD

**Issue by JSoko** [strukturag/nextcloud-spreedme#38]
update to Spreed.ME 0.2.0 workes, but it seems to overwrite
/apps/spreedme/extra/static/config/OwnCloudConfig.js
and
/apps/spreedme/config/config.php

So after upgrade you have to restore the old files or 

cd /var/www/owncloud/apps/spreedme/config
Go to the nextcloud spreedme app configuration folder
cp config.php.in config.php
Create the config file from the default file
nano config.php
Edit the config file and make these modifications:
Set SPREED_WEBRTC_BASEPATH to /webrtc/: const SPREED_WEBRTC_BASEPATH = '/webrtc/';
Set SPREED_WEBRTC_SHAREDSECRET to the shared secret you generated for the Spreed.ME server configuration above: const SPREED_WEBRTC_SHAREDSECRET = 'bb04fb058e2d7fd19c5bdaa129e7883195f73a9c49414a7eXXXXXXXXXXXXXXXX';
You can choose to modify OWNCLOUD_TEMPORARY_PASSWORD_LOGIN_ENABLED to true to allow your users to invite other, unregistered users for a call. With this on false users need to have a Nextcloud account to join a call. If you enable it, generate a new random string and put it below, see the included instructions.
Now save and close the file.
cd /var/www/owncloud/apps/spreedme/extra/static/config
Go to the nextcloud spreedme app extra/static/config folder
cp OwnCloudConfig.js.in OwnCloudConfig.js
Create the javascript config file
If you put Spreed.ME in /webrtc/ (as this manual assumes), you don't need to make any other changes. If you put it in its own domain you have to edit the file and make sure you set OWNCLOUD_ORIGIN to your Nextcloud server.

**Comment by longsleep** [comment]
@leonklingele can we do something about this overwriting problem?

**Comment by leonklingele** [comment]
@JSoko
Please see https://github.com/strukturag/nextcloud-spreedme#upgrading-this-app

@longsleep
We could store all settings from `config.php` in the NC database.
The settings of `OwnCloudConfig.js` however can't be stored in the database.
`OwnCloudConfig.js` currently is only needed to tell Spreed WebRTC where it can find the NC host. If we completely deprecate support for setting up NC/oC on two different hosts / NC/oC in a subpath, we can remove this file.

**Comment by JSoko** [comment]
@leonklingele 
Thank You for the hint, but IMHO spreed.ME is the first app which does the upgrade from the store and needs to be configured again afterwards.

So if you wont go the way, you mentioned to @longsleep IMHO before doing the upgrade, the user should see an alert and the possibility to stop the update.

And there should be an updatediscription in the appstore too
https://apps.owncloud.com/content/show.php/Spreed.ME?content=174436

**Comment by leonklingele** [comment]
@JSoko have you upgraded the app directly from the web interface or have you downloaded the upgrade manually (e.g. via App Store)?

**Comment by JSoko** [comment]
@leonklingele 
directly from the web interface and had looked before in the appstore what has changed.

I didn't look in the installation guide before updating...

**Comment by longsleep** [comment]
We should try hard to avoid overwriting any user made configuration on update ttw. I also do not see why it actually would overwrite anything as the repository does contain OwnCloudConfig.js.in only and the user is supposed to have copied this. Whats wrong here?

**Comment by leonklingele** [comment]
Well – If the app is upgraded via web interface, NC downloads the tarball of the new release from the oC app store and automatically replaces the whole app folder with it.

In https://github.com/nextcloud/server/issues/880 https://github.com/nextcloud/server/issues/880 we might find a solution for this issue.

**Comment by longsleep** [comment]
> replaces the whole app folder with it

Oh i see - then its not a bug - thanks for the explanation. Still we need to improve.

**Comment by leonklingele** [comment]
#39 should make it easier to upgrade the app.

**Comment by JSoko** [comment]
@leonklingele 
Now I've done an update to 0.3.1 through the webinterface.

after that, it shows that spreed.me isn't configured

You have to copy and modify config.php in /apps/spreedme/config again...

After that, it works again. The javascript config file now don't have to be touched :-)

Than, In the admin-panel under  nc 9.53 it shows:

> Spreed.ME
> config/config.php was found.
> If you want to change it, you need to edit the file by yourself.
> extra/static/config/OwnCloudConfig.js was not found.
> If you want to run Spreed WebRTC and Nextcloud on different origins, please read this document.

IMHO OwnCloudConfig.js was not found could be read as an erro and should be clarified...

**Comment by leonklingele** [comment]
Well, once you have migrated to the new way to configure the app (via web interface), you will never need to re-configure the app again.
1. Rename `apps/spreedme/config/config.php` to e.g. `apps/spreedme/config/config-old.php`
2. Open /index.php/settings/admin#goto-spreed.me in your browser
3. Click **Generate new shared secret** and copy the secret to your clipboard
4. Click **Save settings**
5. Head over to Spreed WebRTC’s config, and use the new secret for `sharedsecret_secret`
6. Restart Spreed WebRTC. You will never need to re-configure the app again.

**Comment by JSoko** [comment]
Yes, now i've seen it...

great work!
