### ISSUE TITLE
TP expiration date field not present

### ISSUE THREAD

**Issue by danielepercivaldi** [strukturag/nextcloud-spreedme#4]
In the window for defining temporary password there is only "expiration" label and NOT the field. (See attached image), so you cannot enter expiration date.

![image](https://cloud.githubusercontent.com/assets/8720648/12380825/3de01f74-bd7c-11e5-851a-6add359ed2e0.png)

**Comment by leonklingele** [comment]
Hmm, this looks strange.
Can you provide additional information about your setup (Browser + version, version of this plugin, ..)?

Thank you :rocket:

**Comment by danielepercivaldi** [comment]
Hi.
The error occurs in both Firefox 43.0.4 and Chrome 47.0.2526.111 m.
The owncloud app version is 0.1.1 (latest one published some days ago)
Owncloud 8.1.5 stable
Spreed-webrtc-server version is  0.24.9-1~trusty1 (packaged version).
Apache 2.4.7
Ubuntu 14.04.03 LTS 64bit
PHP 5.5.9

Thank you for your help.

Bye, Daniele

**Comment by leonklingele** [comment]
Issue has been resolved in https://github.com/strukturag/owncloud-spreedme/commit/28c4fbf7998a4f3653394d88e123b93f6861e81e A new release will be pushed soon.

Thanks for using this plugin, Daniele :)

**Comment by danielepercivaldi** [comment]
Hi.
Thank you for fixing it. Now the field appears.
You can see in attached images that the calendar is not visible/accessible unless you scroll down the window using the mouse wheel ONLY. If you clic on scroll bar the calendar disappears.
I think it's better the calendar stays in foreground, no?
Besides: can you set the default date format according to computer local settings (i.e.: in my case dd/mm/yyyy HH:mm)?
![tpepf1](https://cloud.githubusercontent.com/assets/8720648/12433889/df8048ee-bf03-11e5-8ff6-5d29f5fb482b.jpg)
![tpepf2](https://cloud.githubusercontent.com/assets/8720648/12433894/e3c935f0-bf03-11e5-8ee9-3986ff505773.jpg)

Thank you for your job.

**Comment by leonklingele** [comment]
The misaligned datepicker issue has been fixed in https://github.com/strukturag/owncloud-spreedme/commit/02d677603e561e73fc306b99deb79675c908af32.
It looks like you have only cherry-picked the fix for the hidden expiration field (https://github.com/strukturag/owncloud-spreedme/commit/28c4fbf7998a4f3653394d88e123b93f6861e81e).
I will push out a new release (0.1.2) tomorrow so you can get an app store version with all the fixes.

Thanks for suggesting the locale dependent date format, will work on this. :)

**Comment by danielepercivaldi** [comment]
Hi.
Just installed it.
Thank you for fixing.
Well, I'm not a developer, so, forgive me if I seem to be pretentious.
What do you think about the appearance in attached images? I think people expects that kind of results.
![tpepf2](https://cloud.githubusercontent.com/assets/8720648/12461547/c6fa6a50-bfb9-11e5-8db7-dfc62220e22b.jpg)
![tpepf3](https://cloud.githubusercontent.com/assets/8720648/12461562/dc0acaca-bfb9-11e5-80fc-a09d5a5fe2d2.jpg)

Well, you see, I don't like scrollbars ...

Thank you for your undestanding.

**Comment by leonklingele** [comment]
Hi Daniele,

the idea on your second image unfortunately does not work.
Everything you see in the "Generate Temporary Password" modal is a website (spreedme/admin/tp) loaded in an Iframe. Hence, we can't put any content (the datepicker) outside of it.

Regarding the first image:
So you want to move the "Generate" button to the bottom right? Sure. I'll think about it. This way will probably be more consistent.
To which scrollbars are you referring to with `I don't like scrollbars`? There should be no scrollbars in the latest version 0.1.2.

**Comment by danielepercivaldi** [comment]
Hi Leon.
Thank you for answering.
About scrollbars:
1. ```
    When TP window opens there is a scrollbar
   ```
   
   ![tpepf1](https://cloud.githubusercontent.com/assets/8720648/12463386/817f8cda-bfc3-11e5-8c57-13404801c8b8.jpg)
2. ```
    When calendar appears there is a scrollbar so you can scroll down the windows to access “Done” and “Now” buttons
   ```
   
   ![tpepf2](https://cloud.githubusercontent.com/assets/8720648/12463394/8af09ba6-bfc3-11e5-8094-626d6f7fba09.jpg)

I think you could make the window taller than now in order to solve it.

Bye, Daniele

P.S.: it happens only in Chrome (just figured out now)

**Comment by leonklingele** [comment]
Can't see the two images.
Apparently you can't attach images to an email that will then appear on GH. :(

**Comment by intresrl** [comment]
Just fixed my previous comment with images.
Thanks.

**Comment by leonklingele** [comment]
Definitely very strange once again.

Can you please try if this potential fix really fixes the issue for you:
In the `extra/static/css/owncloud.css` file modify `height: 340px;` to `height: 340px !important;`
This line: https://github.com/strukturag/owncloud-spreedme/blob/15db689ce9ee9be11a80a65fa6ed8375781e994d/extra/static/css/owncloud.css#L58

**Comment by danielepercivaldi** [comment]
Wow! Now it's fine! Both in Chrome and Firefox.
In Firefox there are some issues with labels and fields alignment, but it works now.
![tpepf1](https://cloud.githubusercontent.com/assets/8720648/12479626/af32ef90-c03c-11e5-81a9-cf04d7b3a3e3.jpg)
![tpepf2](https://cloud.githubusercontent.com/assets/8720648/12479631/b5d0fa9a-c03c-11e5-9ea3-42859778a544.jpg)

**Comment by leonklingele** [comment]
Issue resolved in https://github.com/strukturag/owncloud-spreedme/commit/1d2d7cc33e5c633905812eb126a52f619956b9ee

**Comment by danielepercivaldi** [comment]
Hi Leon.
Thank you very much for your effort.
I have a suggestion for the future about TP.
You know, only administrators can generate tp.
What about if you allow also users that manage other user groups (see attached image)?
![tpepf1](https://cloud.githubusercontent.com/assets/8720648/12516915/5c245754-c130-11e5-88ca-f46479a911ba.jpg)

**Comment by leonklingele** [comment]
Already have this on my agenda.
Thank you for your great suggestions!
