### ISSUE TITLE
after Update to 0.3.1: "Could not authenticate. Please try again."

### ISSUE THREAD

**Issue by BurtGummer** [strukturag/nextcloud-spreedme#42]
Hello,

i update the spreed.me App to the version 0.3.1 over Nextcloud -> Apps.
then i enter the Spreed.me app an there was an error. I should configure the app in the Admin-Interface. OK, i have done this and make a "cp config.php.in config.php" because the old file was deletet with the upgrade (?). I have change the "const SPREED_WEBRTC_SHAREDSECRET = 'XXX'" setting in comfig.php.

Now, i get the spreed.me Page again but i get the note "Could not authenticate. Please try again.". The log say:

`Exception: {"Exception":"Exception","Message":"No user available for the given login name.","Code":0,"Trace":"#0 \/var\/www\/nextcloud\/apps\/user_ldap\/user_ldap.php(120): OCA\\user_ldap\\USER_LDAP->getLDAPUserByLoginName('(null)')\n#1 \/var\/www\/nextcloud\/lib\/private\/user\/manager.php(189): OCA\\user_ldap\\USER_LDAP->checkPassword(*** username and password replaced ***)\n#2 \/var\/www\/nextcloud\/lib\/private\/user\/session.php(219): OC\\User\\Manager->checkPassword(*** username and password replaced ***)\n#3 \/var\/www\/nextcloud\/lib\/private\/user.php(162): OC\\User\\Session->login(*** username and password replaced ***)\n#4 \/var\/www\/nextcloud\/lib\/private\/api.php(359): OC_User::login(*** username and password replaced ***)\n#5 \/var\/www\/nextcloud\/lib\/private\/api.php(297): OC_API::loginUser()\n#6 \/var\/www\/nextcloud\/lib\/private\/api.php(156): OC_API::isAuthorised(Array)\n#7 [internal function]: OC_API::call(Array)\n#8 \/var\/www\/nextcloud\/lib\/private\/route\/router.php(276): call_user_func(Array, Array)\n#9 \/var\/www\/nextcloud\/ocs\/v1.php(54): OC\\Route\\Router->match('\/ocs\/cloud\/capa...')\n#10 {main}","File":"\/var\/www\/nextcloud\/apps\/user_ldap\/user_ldap.php","Line":105}`

The console from the Browser say:

`Failed to load resource: the server responded with a status of 403 (Forbidden)`

I have clear the browser-cache, the ../apache/error.log say nothing.

I have change nothing, any ideas whats wrong?

**Comment by leonklingele** [comment]
Hi @BurtGummer,

yes, the config files are lost during an upgrade via the Nextcloud web interface.
There’s nothing we can do about that. That’s why we added a new way to configure the app:
Via the Nextcloud Admin web interface. This way, you will not need to reconfigure the app after upgrades.

Simply delete the app’s `config/config.php` and follow the installation steps again:
https://github.com/strukturag/nextcloud-spreedme#installation--setup-of-this-app
