### ISSUE TITLE
Screen sharing issues

### ISSUE THREAD

**Issue by BDub-Hay** [strukturag/nextcloud-spreedme#43]
Hello, I have a working installation of Spreed.me on my nextcloud installation.  I am having issues getting the screen share to work.  I am using the most recent version of firefox (48.0.2).  I checked the webrtc config file to make sure the module is enabled.  i even restarted for good measure.  I can use the  presentation module, and the youtube module just fine but when i try to use the screen share i get "Failed to start screen sharing (SecurityError)" on one machine and "Permission to start screen sharing was denied" on another machine.  Any suggestions would be greatly appreciated.  Thanks.

**Comment by longsleep** [comment]
Firefox uses a whitelist approach to allow screen sharing. Custom domains need to be added manually to that white list. See https://github.com/strukturag/spreed-webrtc#firefox for instructions on how to do this.

**Comment by BDub-Hay** [comment]
> Firefox uses a whitelist approach to allow screen sharing. Custom domains need to be added manually to that white list. See https://github.com/strukturag/spreed-webrtc#firefox for instructions on how to do this.

Excellent, I didn't even think to check that.  Thank you very much.
