### ISSUE TITLE
 Feature: choosing a roomtype when creating a room

### ISSUE THREAD

**Issue by jgrete** [strukturag/nextcloud-spreedme#44]
Nice feature would be to have a checkbox **[ ] Conference** in the room  dialog. The result should be the prepending of "conference" to the roomname (auto or manually generated).
Even better would be a listbox for choosing one of the roomtypes (up to now the names of the conference types).
And absolutly TOP would be to have more roomtypes. For example:
- Limited rooms (limited by nextcloud groups or user accounts)
- Public predefined rooms (Lounge, Juergen's office,...)

Just some thoughts :-)
Juergen

**Comment by aostrovsky** [comment]
+1
Predefined list of conf rooms with per group access.
Use case. Number of different projects with attached conf rooms. People are in per projects groups as well.
So members of groups have list of allowed for them rooms.

**Comment by jgrete** [comment]
After 1 year I think I can close it...
Maybe future integrations will offer similar features
