### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by fancycode** [strukturag/nextcloud-spreedme#5]
I just noticed that Travis is not enabled for this project even though there is a `.travis.yml` file.

Is there a reason for that or can I just enable it?

**Comment by leonklingele** [comment]
Yes, as soon as this project gets some useful unit tests :)

**Comment by fancycode** [comment]
Well, there is at least one test that checks if the app gets installed - if that works Travis will be green ;-) We can always add more tests later...

**Comment by leonklingele** [comment]
Sure. Removed the other tests in https://github.com/strukturag/owncloud-spreedme/commit/68756b5e1a1c7f7b1b29cacdc0b12ca22c41ae26 so Travis should not fail.

Whoops, and please enable Travis :smile:

**Comment by leonklingele** [comment]
Reopening as build fails due to missing config files. Will work on this later.

**Comment by leonklingele** [comment]
@fancycode Can you please enable Travis?

**Comment by fancycode** [comment]
It's enabled now but failing:
https://travis-ci.org/strukturag/owncloud-spreedme

Please create a pull-request where you fix any issues and once Travis is green on the PR, squash it and merge to master.
