### ISSUE TITLE
No base path included after error msgbox/redirection

### ISSUE THREAD

**Issue by jgrete** [strukturag/nextcloud-spreedme#51]
Hi,
when following an invitation without preceding authorization I'm getting an error
"Please log in into your Nextcloud account to use use this service." After clicking "OK"
I'm redirected to the server URL and have to append the whole string manually or copy and paste the invitation link. It would be much easier if the invited person is redirected to the proper room and any  authorization needed would be made "on the way" - meaning no stop after authorization, manually choose Spreed.Me from the menu, enter room ID and so on...

A quick scroll through owncloud.js shows that there are some review comments concerning this matter :-)

I submitted this issue to show it's relevance - my people are not exactly computer affine...

Than you
Juergen

**Comment by leonklingele** [comment]
If should only see the `Please log in into your Nextcloud account to use use this service.` message if you haven’t enabled the temporary password feature.
Are you trying to invite someone who already has an account on your Nextcloud installation but is not logged in?

**Comment by jgrete** [comment]
My invitation is the room link which I posted by email. The invited person is not logged in (but has an account) and get's the message box "Please log in...". Clicking the CLOSE button leads to the base URL (not to the proper room).
My proposal at this point would be to let the user log in and then leading her/him to the proper room. 
It's just "rounding" some rough edges :-)

**Comment by leonklingele** [comment]
Please try 70f2d827daf720794c2707ec08d3778a96937f76 :)

**Comment by leonklingele** [comment]
Fix is included in the latest 0.3.3 release.
