### ISSUE TITLE
Content Security Policy: The page’s settings blocked the loading of a resource at self

### ISSUE THREAD

**Issue by drhirn** [strukturag/nextcloud-spreedme#52]
Hi,

installed Spreed WebRTC and the Nextcloud SpreedMe App following the documentation here.

When calling the SpreedMe App with Firefox I get the following messages:
`Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://... 'unsafe-eval'”).`
and
`Firefox can’t establish a connection to the server at wss://tlocvie01.dmz.bka.gv.at/webrtc/ws.`

And with Chrome:
`Refused to execute script from 'https://.../webrtc/static/ver=1476194750/js/libs/require/require.js' because its MIME type ('text/x-js') is not executable, and strict MIME type checking is enabled.`

In both cases the app doesn't start.

Did I do something wrong?

Thx
Stefan

**Comment by leonklingele** [comment]
Hi @drhirn,

`Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://... 'unsafe-eval'”).`
This error can be ignored — it’s a known bug when using ownCloud/Nextcloud with Firefox :)

The other two error messages look suspicious. Can you please post the configuration of your web server?

**Comment by drhirn** [comment]
Hi @leonklingele,

found out today, that both "suspicious" messages must have something to do with SLES11 SP4 (which is quite old). Did the same installation again with CentOS 7 and everything's working great.

So I think, this can be ignored. But if you're still interested, I'll post the configuration.

Thx
Stefan

**Comment by leonklingele** [comment]
I guess you’re using Apache. Which version of it is installed on your SLES11?
You need at least Apache version 2.4.5 to be able to proxy the Websocket protocol.

**Comment by drhirn** [comment]
That was exactly my suspicion. SLES11 still uses Apache 2.2.
