### ISSUE TITLE
Room link is lacking scheme://hostname:port

### ISSUE THREAD

**Issue by longsleep** [strukturag/nextcloud-spreedme#53]
The patched room link generator is not generating complete URLs. The scheme and host are missing. It generates links like `/apps/spreedme#abc`.

https://github.com/strukturag/nextcloud-spreedme/blob/develop/extra/static/owncloud.js#L123-L138

**Comment by leonklingele** [comment]
It should get the base URL (incl. scheme, hostname and port) from 'ownCloud.getConfig().baseURL'.
Please make sure to disable/flush your browser cache and/or increase the app version which will have the same effect.

**Comment by longsleep** [comment]
Well, this is a fresh install. Browser cache is disabled.

**Comment by leonklingele** [comment]
Duplicate of #48 which already got fixed.
