### ISSUE TITLE
Spreed.ME Webrtc Page Blank

### ISSUE THREAD

**Issue by Rommyhadi2406** [strukturag/nextcloud-spreedme#59]
Hai,

I just install my nextcloud on Ubuntu Server 14.04, and im interested to install the spreed me apps, i followed all the instructions with the apache guidance, but when i clicked the spreed.me apps, i always got the spreed.me blank page, like this picture below

![2016-11-09_9-27-03](https://cloud.githubusercontent.com/assets/23349746/20125260/fc47a9ac-a65e-11e6-8f42-1588a25ccc80.png)

could you tell me what seems to be wrong?? im having this problem for two weeks, and it makes me nutz...

Thanks,

**Comment by leonklingele** [comment]
Hi,

please verify that the `index.php/apps/spreedme/admin/debug` endpoint returns `Passed all tests.`
Additionally, can you please post your config files?

**Comment by Rommyhadi2406** [comment]
Hi Leon,

i just tried as you told me, and this is the result

Spreed.ME Version 0.3.3

Ran test #1 (testOwncloudPhpConfigFile):
   Passed without an error

Ran test #2 (testOwncloudJavascriptConfigFile):
   Passed without an error

Ran test #3 (testSpreedWebRTCAPI):
   Error: Unable to connect to WebRTC at http://my_domain_name/webrtc/. Did you set a correct SPREED_WEBRTC_ORIGIN and SPREED_WEBRTC_BASEPATH in config/config.php?

Some tests failed. :(

what is the right path should i fill in SPREED_WEBRTC_ORIGIN and SPREED_WEBRTC_BASEPATH config?

#config.php.in 
<?php
/**
- Nextcloud - spreedme
  *
- This file is licensed under the Affero General Public License version 3 or
- later. See the COPYING file.
  *
- @author Leon leon@struktur.de
- @copyright struktur AG 2016
  */

namespace OCA\SpreedME\Config;

class Config {

```
    // Domain of your Spreed WebRTC server (including protocol and optional port number), examples:
    //const SPREED_WEBRTC_ORIGIN = 'https://mynextcloudserver.com';
    //const SPREED_WEBRTC_ORIGIN = 'https://webrtc.mynextcloudserver.com:8080';
    // If this is empty or only includes a port (e.g. :8080), host will automatically be determined (current host)
    const SPREED_WEBRTC_ORIGIN = 'https://oncloud.arthatel.co.id';

    // This has to be the same `basePath`
    // you already set in the [http] section of the `server.conf` file from Spreed WebRTC server
    const SPREED_WEBRTC_BASEPATH = '/webrtc';

    // This has to be the same `sharedsecret_secret` (64-character HEX string)
    // you already set in the [users] section of the `server.conf` file from Spreed WebRTC server
    const SPREED_WEBRTC_SHAREDSECRET = 'ac1059a7b77c5b8bd1956fda02cc8b1d7c2ac73aeeb74dd849121297472736df';

    // Set to true if at least one another Nextcloud instance uses the same Spreed WebRTC server
    const SPREED_WEBRTC_IS_SHARED_INSTANCE = false;

    // Set to true if you want to allow access to this app + spreed-webrtc for non-registered users who received a temporary password by an Nextcloud admin.
    // You can generate such a temporary password at: /index.php/apps/spreedme/admin/tp (Nextcloud admin user account required)
    const OWNCLOUD_TEMPORARY_PASSWORD_LOGIN_ENABLED = false;

    // If 'OWNCLOUD_TEMPORARY_PASSWORD_LOGIN_ENABLED' is set to true, you also have to provide a signing key here (64-character HEX string)
    // Generate it using `xxd -ps -l 32 -c 32 /dev/random` (better) or `openssl rand -hex 32`
    const OWNCLOUD_TEMPORARY_PASSWORD_SIGNING_KEY = 'f20e1b84781d80570fef6e2969f61ba91ccb56922398a45eXXXXXXXXXXXXXXXX';

    private function __construct() {

    }
```

}

Thnks,

**Comment by leonklingele** [comment]
Can you please follow these steps:
- Open the Spreed.ME app in Nextcloud
- Append ?debug to the URL, i.e. https://domain.com/index.php/apps/spreedme/?debug
- Now open your browser’s dev console:
- Right click on the Nextcloud site
- Click "Inspect element" (very bottom)
- Check what it says in the console and paste it here

`SPREED_WEBRTC_ORIGIN` can be set to an empty string (`const SPREED_WEBRTC_ORIGIN = '';`) as your Spreed WebRTC runs on the same domain as your Nextcloud.

Are you sure you have started the WebRTC server? https://oncloud.arthatel.co.id/webrtc says `Service Unavailable`..

**Comment by Rommyhadi2406** [comment]
Hi Leon,

I followed the steps, and the result is 

![image](https://cloud.githubusercontent.com/assets/23349746/20253044/30ed4dac-aa5a-11e6-9fc1-5f177e81a116.png)

need your help please

Thanks

**Comment by leonklingele** [comment]
Hi @Rommyhadi2406,

please post your Apache config.
Does it look similar to our example? https://github.com/strukturag/nextcloud-spreedme/blob/master/doc/example-config-apache.md

**Comment by Rommyhadi2406** [comment]
Hi Leon,

This is my apache2 config

# This is the main Apache server configuration file.  It contains the
# configuration directives that give the server its instructions.
# See http://httpd.apache.org/docs/2.4/ for detailed information about
# the directives and /usr/share/doc/apache2/README.Debian about Debian specific
# hints.
#
#
# Summary of how the Apache 2 configuration works in Debian:
# The Apache 2 web server configuration in Debian is quite different to
# upstream's suggested way to configure the web server. This is because Debian's
# default Apache2 installation attempts to make adding and removing modules,
# virtual hosts, and extra configuration directives as flexible as possible, in
# order to make automating the changes and administering the server as easy as
# possible.

# It is split into several files forming the configuration hierarchy outlined
# below, all located in the /etc/apache2/ directory:
#
#       /etc/apache2/
#       |-- apache2.conf
#       |       `--  ports.conf
#       |-- mods-enabled
#       |       |-- *.load
#       |       `-- *.conf
#       |-- conf-enabled
#       |       `-- *.conf
#       `-- sites-enabled
#               `-- *.conf
#
#
# * apache2.conf is the main configuration file (this file). It puts the pieces
#   together by including all remaining configuration files when starting up the
#   web server.
#
# * ports.conf is always included from the main configuration file. It is
#   supposed to determine listening ports for incoming connections which can be
#   customized anytime.
#
# * Configuration files in the mods-enabled/, conf-enabled/ and sites-enabled/
#   directories contain particular configuration snippets which manage modules,
#   global configuration fragments, or virtual host configurations,
#   respectively.
#
#   They are activated by symlinking available configuration files from their
#   respective *-available/ counterparts. These should be managed by using our
#   helpers a2enmod/a2dismod, a2ensite/a2dissite and a2enconf/a2disconf. See
#   their respective man pages for detailed information.
#
# * The binary is called apache2. Due to the use of environment variables, in
#   the default configuration, apache2 needs to be started/stopped with
#   /etc/init.d/apache2 or apache2ctl. Calling /usr/bin/apache2 directly will not
#   work with the default configuration.


# Global configuration
#

#
# ServerRoot: The top of the directory tree under which the server's
# configuration, error, and log files are kept.
#
# NOTE!  If you intend to place this on an NFS (or otherwise network)
# mounted filesystem then please read the Mutex documentation (available
# at <URL:http://httpd.apache.org/docs/2.4/mod/core.html#mutex>);
# you will save yourself a lot of trouble.
#
# Do NOT add a slash at the end of the directory path.
#
#ServerRoot "/etc/apache2"

#
# The accept serialization lock file MUST BE STORED ON A LOCAL DISK.
#
Mutex file:${APACHE_LOCK_DIR} default

#
# PidFile: The file in which the server should record its process
# identification number when it starts.
# This needs to be set in /etc/apache2/envvars
#
PidFile ${APACHE_PID_FILE}

#
# Timeout: The number of seconds before receives and sends time out.
#
Timeout 300

#
# KeepAlive: Whether or not to allow persistent connections (more than
# one request per connection). Set to "Off" to deactivate.
#
KeepAlive On

#
# MaxKeepAliveRequests: The maximum number of requests to allow
# during a persistent connection. Set to 0 to allow an unlimited amount.
# We recommend you leave this number high, for maximum performance.
#
MaxKeepAliveRequests 100

#
# KeepAliveTimeout: Number of seconds to wait for the next request from the
# same client on the same connection.
#
KeepAliveTimeout 5


# These need to be set in /etc/apache2/envvars
User ${APACHE_RUN_USER}
Group ${APACHE_RUN_GROUP}

#
# HostnameLookups: Log the names of clients or just their IP addresses
# e.g., www.apache.org (on) or 204.62.129.132 (off).
# The default is off because it'd be overall better for the net if people
# had to knowingly turn this feature on, since enabling it means that
# each client request will result in AT LEAST one lookup request to the
# nameserver.
#
HostnameLookups Off

# ErrorLog: The location of the error log file.
# If you do not specify an ErrorLog directive within a <VirtualHost>
# container, error messages relating to that virtual host will be
# logged here.  If you *do* define an error logfile for a <VirtualHost>
# container, that host's errors will be logged there and not here.
#
ErrorLog ${APACHE_LOG_DIR}/error.log

#
# LogLevel: Control the severity of messages logged to the error_log.
# Available values: trace8, ..., trace1, debug, info, notice, warn,
# error, crit, alert, emerg.
# It is also possible to configure the log level for particular modules, e.g.
# "LogLevel info ssl:warn"
#
LogLevel warn

# Include module configuration:
IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf

# Include list of ports to listen on
Include ports.conf


# Sets the default security model of the Apache2 HTTPD server. It does
# not allow access to the root filesystem outside of /usr/share and /var/www.
# The former is used by web applications packaged in Debian,
# the latter may be used for local directories served by the web server. If
# your system is serving content from a sub-directory in /srv you must allow
# access here, or in any related virtual host.
<Directory />
        Options FollowSymLinks
        AllowOverride None
        Require all denied
</Directory>

<Directory /usr/share>
        AllowOverride None
        Require all granted
</Directory>

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>

#<Directory /srv/>
#       Options Indexes FollowSymLinks
#       AllowOverride None
#       Require all granted
#</Directory>




# AccessFileName: The name of the file to look for in each directory
# for additional configuration directives.  See also the AllowOverride
# directive.
#
AccessFileName .htaccess

#
# The following lines prevent .htaccess and .htpasswd files from being
# viewed by Web clients.
#
<FilesMatch "^\.ht">
        Require all denied
</FilesMatch>


#
# The following directives define some format nicknames for use with
# a CustomLog directive.
#
# These deviate from the Common Log Format definitions in that they use %O
# (the actual bytes sent including headers) instead of %b (the size of the
# requested file), because the latter makes it impossible to detect partial
# requests.
#
# Note that the use of %{X-Forwarded-For}i instead of %h is not recommended.
# Use mod_remoteip instead.
#
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent

# Include of directories ignores editors' and dpkg's backup files,
# see README.Debian for details.

# Include generic snippets of statements
IncludeOptional conf-enabled/*.conf

# Include the virtual host configurations:
IncludeOptional sites-enabled/*.conf

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

so, if i add the lines from the example, reload and restart the apache, it will show the service unavailable page, but if i use the default configuration, it show Not Found The requested URL /webrtc/ was not found on this server. 

what shoul i do?

Thanks

**Comment by leonklingele** [comment]
You need to include the lines from our example. You get the `Service Unavailable` error message because it can’t connect to spreed-webrtc.
Did you [install, configure & start spreed-webrtc](https://github.com/strukturag/nextcloud-spreedme#installation--setup-of-a-spreed-webrtc-server) on your server?

**Comment by Rommyhadi2406** [comment]
Hi Leon,

I tried to start the spreed-webrtc-server, and there was an error in the TLS section, what should i do?

![2016-11-22_10-48-35](https://cloud.githubusercontent.com/assets/23349746/20510225/832e292c-b0a1-11e6-9403-b10623648bc3.png)

Thanks,
Regards,

**Comment by Rommyhadi2406** [comment]
Hi Leon, 

At last, i have succeded install the spreedme webrtc to my nextcloud

Thank you so much for your help

Regards
