### ISSUE TITLE
own status message

### ISSUE THREAD

**Issue by danielepercivaldi** [strukturag/nextcloud-spreedme#6]
Hi.
I think it could be very nice to see my own status message in the header (see image).
What about it?
![spreedme](https://cloud.githubusercontent.com/assets/8720648/12677706/2ca4d452-c69b-11e5-9d1b-d77ca6cec0ef.jpg)

**Comment by leonklingele** [comment]
Actually, this is a feature request related to [spreed-webrtc](https://github.com/strukturag/spreed-webrtc) (the conferencing server) and not this app.
Can you please re-open the issue over there? :) Thank you :whale:

**Comment by danielepercivaldi** [comment]
Hi.
Done! Let's see their reaction! :)
