### ISSUE TITLE
update to 0.3.4

### ISSUE THREAD

**Issue by JSoko** [strukturag/nextcloud-spreedme#61]
### Expected behaviour
Spreed.me should update

### Actual behaviour
extcloud shows "A update to spreed.Me 0.3.4 is available"
Under apps, no Update is available
Log shows:
Could not get application: cURL error 60: SSL certificate problem: unable to get local issuer certificate

web-rtc has bin updated:
```
Preparing to unpack .../spreed-webrtc-bin_0.29.3-1~trusty2_armhf.deb ...
Unpacking spreed-webrtc-bin (0.29.3-1~trusty2) over (0.29.3-1~trusty1) ...
Preparing to unpack .../spreed-webrtc_0.29.3-1~trusty2_all.deb ...
Unpacking spreed-webrtc (0.29.3-1~trusty2) over (0.29.3-1~trusty1) ...
Preparing to unpack .../spreed-webrtc-assets_0.29.3-1~trusty2_all.deb ...
Unpacking spreed-webrtc-assets (0.29.3-1~trusty2) over (0.29.3-1~trusty1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up spreed-webrtc-bin (0.29.3-1~trusty2) ...
Setting up spreed-webrtc-assets (0.29.3-1~trusty2) ...
Setting up spreed-webrtc (0.29.3-1~trusty2) ...
```

### Server configuration
**Operating system**: Linux OdOc 3.10.96 #1 SMP PREEMPT Mon May 23 01:50:06 BRT 2016 armv7l

**Web server:**  apache2handler

**Database:** mysql
MariaDB
**PHP version:** 7.0.8-0ubuntu0.16.04.3

**Nextcloud version:** 9.1.1.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**List of activated apps:**
<details>
	<summary>App list</summary>

	```
	Enabled:
	 - activity: 2.3.2
	 - admin_audit: 1.0.0
	 - bookmarks: 0.9.0
	 - calendar: 1.4.0
	 - comments: 1.0.0
	 - contacts: 1.4.0.0
	 - dav: 1.0.1
	 - direct_menu: 0.9.2
	 - federatedfilesharing: 1.0.1
	 - files: 1.5.2
	 - files_pdfviewer: 0.8.1
	 - files_sharing: 1.0.0
	 - files_texteditor: 2.1
	 - files_trashbin: 1.0.0
	 - files_versions: 1.3.0
	 - files_videoplayer: 0.9.8
	 - flowupload: 0.3
	 - html5_videoplayer: 1.0
	 - issuetemplate: 0.0.1
	 - keeweb: 0.2.9
	 - logreader: 1.1.5
	 - news: 9.0.4
	 - nextnotes: 0.9.1
	 - notifications: 0.3.0
	 - ocsms: 1.10.1
	 - ownbackup: 0.3.8
	 - password_policy: 1.0.0
	 - provisioning_api: 1.0.0
	 - serverinfo: 1.1.1
	 - shorten: 0.0.15
	 - spreedme: 0.3.3
	 - survey_client: 0.1.5
	 - tasks: 0.9.3
	 - templateeditor: 0.1
	 - theming: 1.0.1
	 - updatenotification: 1.0.1
	 - workflowengine: 1.0.1

	Disabled:
	 - encryption
	 - external
	 - federation
	 - files_accesscontrol
	 - files_automatedtagging
	 - files_external
	 - files_retention
	 - firstrunwizard
	 - gallery
	 - qownnotesapi
	 - systemtags
	 - user_external
	 - user_ldap
	 - user_saml
	```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "default_language": "de_DE",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "\/var\/www\/owncloud\/data",
    "tempdirectory": "\/media\/ssd\/phptemp\/",
    "dbtype": "mysql",
    "version": "9.1.1.5",
    "theme": "",
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "integrity.check.disabled": false,
    "dbname": "owncloud",
    "dbhost": "127.0.0.1",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": 2,
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 500000,
    "cron_log": true,
    "asset-pipeline.enabled": false,
    "assetdirectory": "\/var\/www\/owncloud",
    "maxZipInputSize": 2147483648,
    "overwritewebroot": "\/",
    "overwrite.cli.url": "\/",
    "htaccess.RewriteBase": "\/",
    "allowZipDownload": true,
    "versions": "true",
    "versions_retention_obligation": "1,3",
    "instanceid": "5072f7e9eec7e",
    "knowledgebaseenabled": true,
    "check_for_working_webdav": true,
    "check_for_working_htaccess": true,
    "check_for_working_wellknown_setup": true,
    "has_internet_connection": true,
    "forcessl": true,
    "activity_expire_days": 8,
    "appcodechecker": false,
    "skeletondirectory": "",
    "trashbin_retention_obligation": "auto,15",
    "appstore.experimental.enabled": true,
    "trusted_domains": [
        "***.net",
        "***.net",
        "192.168.1.234"
    ],
    "mail_smtpmode": "smtp",
    "mail_smtphost": "smtp.***.de",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "no-reply",
    "mail_domain": "***.de",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
{"reqId":"5QjPhA2ZDQkf\/oX1XKh5","remoteAddr":"192.168.1.**","app":"core","message":"Could not get application: cURL error 60: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2016-11-22T08:49:33+01:00","method":"GET","url":"\/index.phpapps\/list?category=enabled&includeUpdateInfo=1","user":"******"}
(END)

	Insert your Nextcloud log here
	```
</details>

**Comment by leonklingele** [comment]
> Could not get application: cURL error 60: SSL certificate problem: unable to get local issuer certificate

This looks like an issue with the Nextcloud update system. Have you tried to update other apps? Did they fail as well?
Please re-open this issue on the Nextcloud Github repo: https://github.com/nextcloud/server/issues

**Comment by JSoko** [comment]
Until now other apps updated without issue...
...I didn't point nextcloud to the nextcloud-appstore. Until now it loads from the owncloud app-store...

https://github.com/nextcloud/server/issues/2269

**Comment by MorrisJobke** [comment]
> This looks like an issue with the Nextcloud update system. Have you tried to update other apps? Did they fail as well?

Not really - it's because the file to download point to apps.owncloud.com which has a not fully valid SSL cert :(

**Comment by leonklingele** [comment]
ownCloud should simply fix their SSL stuff. Uploading the release to another host doesn't help anyone still using the ownCloud app store.

**Comment by LukasReschke** [comment]
> ownCloud should simply fix their SSL stuff. Uploading the release to another host doesn't help anyone still using the ownCloud app store.

True. But we should also _not_ host stuff on apps.nextcloud.com on ownCloud infrastructure. Just upload it to GitHub releases or so…

**Comment by JSoko** [comment]
Do I understand that right? I've installed spreed in a way it's not supported by nextcloud anymore?

How can / shall I change my system, so that spreed.me is supported by nextcloud again?

My problem is not to update spree.Me 0.3.4 manually, but I wonder if I have misconfigurated something...

**Comment by leonklingele** [comment]
@JSoko everything should work again soon — No need to change anything. Just wait a bit until ownCloud has fixed their app store certificate.

**Comment by leonklingele** [comment]
https://github.com/owncloud/owncloud.org/issues/1105

**Comment by JSoko** [comment]
Thank You Leon for your clear advice,

I was a little bit worried about Lukas Statement  

> But we should also not host stuff on apps.nextcloud.com on ownCloud infrastructure.

and moris comment:

> Ah - I mixed that one up with our spreed app. This is the spreed.me app that requires the additional spreed server to run.
> 
> As this is not part of our release -> closing
> 
> @JSoko Sorry for this back and forth, but this is actually an issue with the environment where the archive of this app is hosted. The SSL cert of this server is not fully trusted and we can do very little there. Sorry for the inconvenience. The app author needs to place the app on a properly hosted platform.
