### ISSUE TITLE
Feature: Screen share a region

### ISSUE THREAD

**Issue by jurgenhaas** [strukturag/nextcloud-spreedme#65]
It's so great that you guys have implemented screensharing and it is working so nicely. The two currently available options (full screen or a single app window) should be extended by a third one I guess: share a defined region.

Why this, what's the use case behind it?

Well, especially developers are often using screen sharing to collaborate with other developers or to present stuff to customers or prospects. At the same time, developers are very often if not always working with multiple monitors. With multiple monitors the full screen sharing isn't a goo choice. It shows too much and for the recipients the result is too wide so that they don't recognize anything any more.

On the other hand, a single app window is not enough because most of the time you have to switch between apps to make sense.

The solution would be to either be able to share one of the available screens or to allow the sharing user to select an area that they wanted to share.

I haven't seen such a feature very often but e.g. the "good" old Skype allowed you to do that. But that tool is no option for serious users any longer, for several reasons. That's where Spreed.Me should come in and fill the gap.

Any chance for a feature like this?

**Comment by fancycode** [comment]
We are using the browsers WebRTC functionality to do the screensharing, so we can only share what the browsers provide (which currently is either whole desktop or application window).

For Chrome there is an open feature request to implement region-based sharing (https://crbug.com/668852), I couldn't find something similar for Firefox. Once the browsers have support for region-based sharing, it will be automatically available for Spreed, too.
