### ISSUE TITLE
Spreed.ME 0.3.5 + NC 11.0.1 after fresh upgrade from 11.0.0 → menu not working anymore

### ISSUE THREAD

**Issue by Sanookmakmak** [strukturag/nextcloud-spreedme#68]
Chromium and Firefox

![auswahl_009](https://cloud.githubusercontent.com/assets/24833757/22004890/8ad13ff4-dc5f-11e6-8b4d-22678b1c77e0.png)

**Comment by leonklingele** [comment]
The app works fine for me on Nextcloud 11.0.1. As this issue occurred for you after upgrading Nextcloud, I assume Nextcloud itself caused the problem.

Please provide additional information about your setup, e.g. did you configure the Spreed.ME app via the admin web interface or the config.php file?
If configured via config.php, check if the file still exists.

**Comment by leonklingele** [comment]
I've just tested the upgrade from NC 11.0.0 to NC 11.0.1: the Spreed.ME app (configured via admin web interface) still works fine.

**Comment by Sanookmakmak** [comment]
> If configured via config.php, check if the file still exists.

That file has disappeared, as well as some other config files (i use ISPconfig).

Now i t seems to work again.

Thank you!
