### ISSUE TITLE
[feature request] "Call to all in room" button

### ISSUE THREAD

**Issue by aostrovsky** [strukturag/nextcloud-spreedme#77]
Idea is to have button which I can push and call to everyone in room.
As it feels annoying to push call on each member if you have let say 10 people in room.

**Comment by leonklingele** [comment]
The `[roomtypes]` configuration option is what you're looking for: https://github.com/strukturag/spreed-webrtc/blob/e483679f0533bbcab063c7721df28c96fe8b86ce/server.conf.in#L216-L228
Each user in a __Conference__ room automatically joins the room call.
