### ISSUE TITLE
Please sign in to create rooms.

### ISSUE THREAD

**Issue by guidtz** [strukturag/nextcloud-spreedme#8]
Hello,

  when I connect to spreed.me plugin I have this message : Please sign in to create rooms.

And so my user is not recognized, i have "me" but not my username.

I configure all like in documentation ! Where is my mistake ?

server.conf 

```
[users]
enabled = true
mode = sharedsecret
sharedsecret_secret ="Iu-****************************************************oo0ree"
allowRegistration = true
```

```
const SPREED_WEBRTC_ORIGIN = 'removed-for-privacy-reasons';
const SPREED_WEBRTC_BASEPATH = '/';
const SPREED_WEBRTC_SHAREDSECRET = 'Iu-********************************************oo0ree';
const OWNCLOUD_TEMPORARY_PASSWORD_LOGIN_ENABLED = true;
const OWNCLOUD_TEMPORARY_PASSWORD_SIGNING_KEY = 'f20e1b84781d80570fef6e2969f61ba91ccb56922398a45eXXXXXXXXXXXXXXXX';
```

Thanks

**Comment by leonklingele** [comment]
Hi guidtz,

as you included the URL to your spreed-webrtc server, I did a quick check:
It tries to load `/var/www/your-domain-here/www/apps/spreedme/extra/static/owncloud.js`, hence something is definitely wrong with your `server.conf`.

Please set
- `plugin = extra/static/owncloud.js`
- `extra = /var/www/your-domain-here/www/apps/spreedme/extra`

**Comment by guidtz** [comment]
Hello,

  this is my server.conf 

```
[http]
listen = 127.0.0.1:8080

[https]

[app]
turnURIs = turn:127.0.0.1:3478?transport=udp
turnSecret = a$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$e
sessionSecret = m$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ae 
encryptionSecret = V$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$T
globalRoom = global
defaultRoomEnabled = true
authorizeRoomJoin = yes 
serverToken = Z$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$Z
serverRealm = local
extra = /var/www/cloud1.domaine.com/www/apps/spreedme/extra 
plugin = /var/www/cloud1.domaine.com/www/apps/spreedme/extra/static/owncloud.js

[modules]
screensharing = true
youtube = true
presentation = true
contacts = true

[log]
logfile = /var/log/spreed-webrtc-server.log

[users]
enabled = true 
mode = sharedsecret
sharedsecret_secret ="I$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$e"
allowRegistration = true 
```

**Comment by leonklingele** [comment]
Please set
- `plugin = extra/static/owncloud.js`
- `extra = /var/www/your-domain-here/www/apps/spreedme/extra` ;)

Do not modify `plugin`, only replace `your-domain-here` with your actual domain.

**Comment by guidtz** [comment]
Ok I haven't got the error but users of owncloud are not recognized 
I have "me" in white status bar
In Profile status I have "Create an account" in front of Your ID

If I click on "Create an account" I have an id like that : 68c2cf09-fb2b-4aae-a543-52a1d4738ee1@local

**Comment by leonklingele** [comment]
Hmm, that's strange. Can you check your browser's developer console logs for any errors?
1. Open the Spreed.ME app in ownCloud
2. Append ?debug to the URL, e.g. https://domain.com/index.php/apps/spreedme/?debug
3. Right click on the ownCloud site
4. Click "Inspect element" (very bottom)
5. Check what it says in the console and paste it here

Thank you

**Comment by guidtz** [comment]
Chrome console infos 

```
wrtc1.domaine.com/static/ver=1456321797/js/main.js:288 Launching ...
wrtc1.domaine.com/static/ver=1456321797/js/main.js:188 Web fonts loaded.
wrtc1.domaine.com/static/ver=1456321797/js/app.js:269 Selected language: en
wrtc1.domaine.com/static/ver=1456321797/js/main.js:275 Bootstrapping ...
wrtc1.domaine.com/static/ver=1456321797/js/services/appdata.js:91 App runtime id: 40piyel
wrtc1.domaine.com/static/ver=1456321797/js/services/mediastream.js:38 Service version: unreleased.1456321797
wrtc1.domaine.com/static/ver=1456321797/js/services/mediastream.js:39 Ws URL: wss://wrtc1.domaine.com/ws
wrtc1.domaine.com/static/ver=1456321797/js/services/mediastream.js:40 Secure Contextual Escaping: true
wrtc1.domaine.com/static/ver=1456321797/js/app.js:164 Initializing ...
wrtc1.domaine.com/extra/static/PostMessageAPI.js:37 PostMessageAPI: POSTING FROM LocationancestorOrigins: DOMStringListassign: ()hash: ""host: "wrtc1.domaine.com"hostname: "wrtc1.domaine.com"href: "https://wrtc1.domaine.com/?debug"origin: "https://wrtc1.domaine.com"pathname: "/"port: ""protocol: "https:"reload: reload()replace: ()search: "?debug"toString: toString()valueOf: valueOf()__proto__: Object TO https://wrtc1.domaine.com Object
wrtc1.domaine.com/static/ver=1456321797/js/services/screensharing.js:237 Screensharing support true autoinstall
wrtc1.domaine.com/static/ver=1456321797/js/services/mediastream.js:240 Initial room path set, continuing to connect ...
wrtc1.domaine.com/static/ver=1456321797/js/services/mediastream.js:231 Ready to connect ...
wrtc1.domaine.com/static/ver=1456321797/js/directives/usability.js:78 Checking for media access ...
wrtc1.domaine.com/static/ver=1456321797/js/directives/usability.js:47 Continue with connect after media check ...
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://wrtc1.domaine.com') does not match the recipient window's origin ('https://cloud1.domaine.com').
wrtc1.domaine.com/static/ver=1456321797/js/app.js:168 Initializing complete.
wrtc1.domaine.com/static/ver=1456321797/js/services/mediastream.js:200 Connecting ...
wrtc1.domaine.com/static/ver=1456321797/js/services/videolayout.js:367 Created new video layout renderer invisible Invisible
wrtc1.domaine.com/static/ver=1456321797/js/mediastream/connector.js:153 Connector on connection open.
wrtc1.domaine.com/extra/static/owncloud.js:64 OC: selfReceived Object
wrtc1.domaine.com/static/ver=1456321797/js/directives/settings.js:197 Disabled video input as no video source was found.
```

https://cloud1.domaine.com is the owncloud url
https://wrtc1.domaine.com is the webrtc proxy url

All are on the same machine with Debian 8 installation, Apache 2.4 and let's encrypt ssl

**Comment by leonklingele** [comment]
Have you set up the `OwnCloudConfig.js` config file?
See step 6 of `Installation / Setup of this app` in the readme file.

**Comment by guidtz** [comment]
Yes 

> If you chose option 1. in the Preparations step above, you can set OWNCLOUD_ORIGIN to an empty string: OWNCLOUD_ORIGIN: '

OWNCLOUD_ORIGIN: '',

So if I force OWNCLOUD_ORIGIN: '', to OWNCLOUD_ORIGIN: 'https://cloud1.domaine.com',

I have this error 
Could not authenticate. Please try again.

Whis this error in console 
`angular.js:8609 PATCH https://wrtc1.domaine.com/api/v1/sessions/MTQ1NjMyNjQxNXxJVkczanVJRFp3TEktY0…xQTY1OVdLNlJsTEpCRFBCWVpnPT182jRMudcFgQomMHwL9FXpCrV8sHcNtucM0c1TXEJUMhs=/ 403 (Forbidden)`

**Comment by leonklingele** [comment]
Well, you did not choose option 1. as you are running spreed-webrtc and OC on two different origins ;)
Can you check the error log of spreed-webrtc, please?

**Comment by guidtz** [comment]
yes sorry I test twice solution and I mix them :-(

spreed-webrtc logs 

```
server 2016/02/24 16:16:18.614288 Error while reading 28 websocket: close 1001 (going away)
server 2016/02/24 16:16:18.614656 Cleaning up client 28 for session id MTQ1NjMyNjQxNXxJVkczanVJRFp3TEktY0FfTHFtN292bEc5TmdEbVhJaUdLejYzazNOUEFzeDVyaTUyX3IxQTY1OVdLNlJsTEpCRFBCWVpnPT182jRMudcFgQomMHwL9FXpCrV8sHcNtucM0c1TXEJUMhs=
server 2016/02/24 16:16:23.224782 Created new session id MTQ1NjMyNjk4M3xXUWRjcGo5MEw1M01GODdDZXJQTm9TbUZHdzl5WjZrRkZacVlENGxfNmdzcTNVM0FmdVBzeW12Y2ptVEE4UFFSb2xkc1ZnPT18VaZ7aecUwHmt4v_Ci1HtHrS09gtq2GW5rMtZc4wbKZY=
server 2016/02/24 16:16:23.224873 Created client 33 with id MTQ1NjMyNjk4M3xXUWRjcGo5MEw1M01GODdDZXJQTm9TbUZHdzl5WjZrRkZacVlENGxfNmdzcTNVM0FmdVBzeW12Y2ptVEE4UFFSb2xkc1ZnPT18VaZ7aecUwHmt4v_Ci1HtHrS09gtq2GW5rMtZc4wbKZY=
server 2016/02/24 16:16:23.224952 Created new session token 556 MTQ1NjMyNjk4M3xQd0xwREFIOVdXVUVIcjBoejVkdnUtSFVxNG5wRVRqYW04TVBLRHZOM0lKcUV3VkhfdmhBY09FR2FZcDNWUU9uLTJkeUs2TWt6U01TcWI4TVNqVDVfWHBvOWNWa1VSRmJuV21ZUnJjMGtwTUp2NmlWUlptUkZnUER1bTdhaEJOaFJaenJsZERxaWtIQzhKM0lKTlJ2N1RBbWdRRTc1bXJxVlROTG5IZnlXd0RXb2F6YmpsclBoMEpzeFBzMFgtN2EwTnh5aG1pOHR1LUlzMmprWFhnRHVPcHN2ampUM0h6YTRqYkhrR2t0NHVkZ2haYWE5VVY4NEpfbmJoRWpTZmRIcFJsYkJMc25FdHBHQlpmU0ttU0Z5bEFmSHhna1NNNUZoVFdweXRSVGlfTDRKY2R0d0g3NUtZWXk2QzYyVU1PUHJkUzRSbkI0VWw4aDBacmZlalVjbjhBYmJLUzc0MWxzbFRuWjNWcWNBdlRxOGxKOVd3PT18oqnnPYza617vjru8QEk0u3vPGi8zeeYG6mjhDF0n_sk=
server 2016/02/24 16:16:23.415722 Session patch failed - users validation failed. invalid secret
server 2016/02/24 16:16:23.415770 Session patch failed - userid empty.
```

**Comment by leonklingele** [comment]
It logs `users validation failed. invalid secret` so I assume `server.conf` and `config.php` are using different shared secrets?

BTW: You can nicely format your logs by putting the text between three backticks ```

**Comment by guidtz** [comment]
euh no
in config.php 
`const SPREED_WEBRTC_SHAREDSECRET = 'Iu-shochaedee@see0quohrie2ieth3ceing(oofeitah3Xaz7ahj8egh>oo0ree';`

in server.conf
`sharedsecret_secret ="Iu-shochaedee@see0quohrie2ieth3ceing(oofeitah3Xaz7ahj8egh>oo0ree"`

My interogation is there are forbiden character in shared secret ?

**Comment by leonklingele** [comment]
> My interogation is there are forbiden character in shared secret ?

Yes, please regenerate the secret and only use HEX characters in it.
You can do this by using one of these commands (prefer the former):
 `xxd -ps -l 32 -c 32 /dev/urandom` or `openssl rand -hex 32`

**Comment by guidtz** [comment]
ok i think is that and perhaps also quote in server.conf 
sharedsecret_secret = "*****"

**Comment by leonklingele** [comment]
Yes, drop the quotes. I really recommend reading the readme ;)
https://github.com/strukturag/owncloud-spreedme/blob/master/README.md#installation--setup-of-this-app

Does it work for you now?

**Comment by guidtz** [comment]
yes It's works I'll go tomorrow to add turn server very nice job.

**Comment by leonklingele** [comment]
Awesome! Feel free to file another issue if you experience further problems.

_Closing ~_
