### ISSUE TITLE
Notice for unanswered call for the call recipient

### ISSUE THREAD

**Issue by kaksikanaa** [strukturag/nextcloud-spreedme#80]
Is it technically possible to make notification about the unanswered calls that remain for
the call recipient if he's/her's browser / session is not closed in mean while?

**Comment by kaksikanaa** [comment]
And to be more specific -> I mean a call where the caller stops the call before the default ringing time is finished (because after that the notification works ok of course).

**Comment by leonklingele** [comment]
Technically it's possible, but it's not implemented yet.
To point you in the right direction: You need to store this information in
your browser's local storage, which is kept across browser restarts.

**Comment by kaksikanaa** [comment]
Ok, we can advice the users to wait if they want to leave this notice to the contact they tried to reach.
