### ISSUE TITLE
Scandinavian letters are broken in Windows chat alert popup

### ISSUE THREAD

**Issue by kaksikanaa** [strukturag/nextcloud-spreedme#81]
Scandinavian letters are broken in Windows chat alert popup when the original chat first characters includes "ä", "å" or "ö" letters.

**Comment by kaksikanaa** [comment]
![capture](https://cloud.githubusercontent.com/assets/15322015/24976724/3fe67920-1fd3-11e7-9253-5259610b1220.JPG)

**Comment by leonklingele** [comment]
I think this was fixed with https://github.com/strukturag/spreed-webrtc/commit/12ebd59ed89169dafc528248f7fed102e5031db5 which is not yet included in a stable release.
Please try a version >= v0.29.2

**Comment by kaksikanaa** [comment]
We have now the version 0.3.9 -> Still same issus when receiving message from iPhone or other browser (Firefox -> Iridium) pls check the attachement. This happens on Win 7 pro.

**Comment by kaksikanaa** [comment]
![capture](https://cloud.githubusercontent.com/assets/15322015/26761458/861f62a6-4938-11e7-816c-e6de88b48e1e.JPG)

**Comment by leonklingele** [comment]
Which version of Spreed WebRTC are you running?
This issue was fixed with Spreed WebRTC v0.29.2

**Comment by kaksikanaa** [comment]
Ah, the server version... it is 0.28.0 so I have to compile it again, thanks!

**Comment by kaksikanaa** [comment]
Jes, this is really fixed on 0.29.0
