### ISSUE TITLE
Users profile pictures do not update regularly

### ISSUE THREAD

**Issue by kaksikanaa** [strukturag/nextcloud-spreedme#83]
It seems that every now and then the users profile pictures do not update regularly to the SpreedMe app. Last resort here is to disconnect all the clients and restart the whole Owncloud + SpreedMe server.

**Comment by leonklingele** [comment]
I wasn't able to reproduce this yet. Please take a look at your browser's
developer console once the bug happens again and post its output.

**Comment by kaksikanaa** [comment]
No reports about this anymore so maybe we can close this one.
