### ISSUE TITLE
temporary password not worky

### ISSUE THREAD

**Issue by ghost** [strukturag/nextcloud-spreedme#86]
Hello Devs.

Tried to acticate the temporary password thing but it did not work as expected. I created a group called Spreed.ME and made me an admin of that. After that i tried to create a temporary passwort at /admin/tp. No reaction on that site when hitting "generate". Logfile says:

`{"reqId":"WSvfI38AAAEAAGgsHqYAAAAb","level":3,"time":"2017-05-29T08:43:15+00:00","remoteAddr":"151.252.43.244","user":"user","app":"index","method":"POST","url":"\/apps\/spreedme\/api\/v1\/admin\/tp","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'OC_Group' not found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/domain.de\\\/htdocs\\\/apps\\\/spreedme\\\/user\\\/user.php(103): OCA\\\\SpreedME\\\\User\\\\User->getGroups()\\n#1 \\\/var\\\/www\\\/domain.de\\\/htdocs\\\/apps\\\/spreedme\\\/user\\\/user.php(115): OCA\\\\SpreedME\\\\User\\\\User->isAdmin()\\n#2 \\\/var\\\/www\\\/domain.de\\\/htdocs\\\/apps\\\/spreedme\\\/controller\\\/apicontroller.php(97): OCA\\\\SpreedME\\\\User\\\\User->isSpreedMeAdmin()\\n#3 [internal function]: OCA\\\\SpreedME\\\\Controller\\\\ApiController->generateTemporaryPassword('test the west', '1496054520')\\n#4 \\\/var\\\/www\\\/domain.de\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/domain.de\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\SpreedME\\\\Controller\\\\ApiController), 'generateTempora...')\\n#6 \\\/var\\\/www\\\/domain.de\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\SpreedME\\\\Controller\\\\ApiController), 'generateTempora...')\\n#7 \\\/var\\\/www\\\/domain.de\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\SpreedME\\\\\\\\Co...', 'generateTempora...', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/var\\\/www\\\/domain.de\\\/htdocs\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/var\\\/www\\\/domain.de\\\/htdocs\\\/lib\\\/base.php(1000): OC\\\\Route\\\\Router->match('\\\/apps\\\/spreedme\\\/...')\\n#11 \\\/var\\\/www\\\/domain.de\\\/htdocs\\\/index.php(40): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/domain.de\\\/htdocs\\\/apps\\\/spreedme\\\/user\\\/user.php\",\"Line\":79}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko\/20100101 Firefox\/53.0","version":"12.0.0.29"}`

**Comment by leonklingele** [comment]
Hi @himbeere,

this has already been fixed with https://github.com/strukturag/nextcloud-spreedme/commit/c6877201c705c54d32b9cc5d0e117ee9f43b3285

I will do a new release of the app now. Sorry for the delay.

**Comment by leonklingele** [comment]
I've released v0.3.9 which includes the fix.
Thanks for reminding me! :)

**Comment by ghost** [comment]
Thanks and you're welcome. :-)
