### ISSUE TITLE
External user 'mark'

### ISSUE THREAD

**Issue by danielepercivaldi** [strukturag/nextcloud-spreedme#9]
External users (invited via 'Temporary Password') are now marked as such. Now, instead of a normal name, for instance, appears something like ext/<testname>/56ddfddfdbc691.13851768 ...

![spreedme](https://cloud.githubusercontent.com/assets/8720648/13602748/cabd4820-e538-11e5-9eb4-7224dd283291.jpg)
![cattura](https://cloud.githubusercontent.com/assets/8720648/13602753/cd434c48-e538-11e5-839a-761dbba593a3.JPG)

**Comment by leonklingele** [comment]
This should not happen; but I was not able to reproduce the issue.
Have you tried to invalidate caches (e.g. restart spreed-webrtc)?

**Comment by danielepercivaldi** [comment]
Restarted. It continues happening.
Here the log in spreed-webrtc:
server 2016/03/08 15:35:54.439252 Session patch successfull MTQ1NzQ0Nzc1NHxXNlhrcXU1NlRqRG4tLWxlZ0ZxQWZJRWFrdHA4M2ZQYVhDSWlKdTF2XzJ6SmNQM2YtWlFoZXBRRHZVZlZqX1dqbWE5OE13PT18GFgXOaHeFx28AGwjDcsBNvfzGBjGMGaKut2pVbjDTEc= -> ext/testname/56dee2faeedbb2.82137404
server 2016/03/08 15:35:54.501559 First session registered for user ext/testname/56dee2faeedbb2.82137404
server 2016/03/08 15:35:54.501587 Authentication success ext/testname/56dee2faeedbb2.82137404

Using:
- owncloud 8.1.5
- spreed-webrtc-server 0.24.12-1~trusty1
- firefox 44.0.2
- chrome 48.0.2564.116 m

**Comment by danielepercivaldi** [comment]
A TP for you in order to test (be patient, my internet connection is quite slow in uploading) valid till 23:50:
https://nerv.net.intre.it/index.php/apps/spreedme?tp=1457477400%3Aext%2FLeon%2F56dee6c1999249.31612307%3A2%3AZIaAhYbMagrva1opz%2FHhvaOXaeKsiobNvVtLP7EGwws%3D

**Comment by leonklingele** [comment]
Just for the records: It turned out to be a caching problem.
Will work on a way to invalidate caches after the plugin was updated.

_Closing ~_
