### ISSUE TITLE
I cannot install version 0.3.10 on oc 9.1.6 and oc 10.0.2

### ISSUE THREAD

**Issue by danielepercivaldi** [strukturag/nextcloud-spreedme#90]
When you try to install version 0.3.10 on oc 9.1.6 you read a message that says the app can hurt ownCloud.
When you try to install it on oc 10.0.2 a message appears that says the app requires oc <= 9.2.

On oc 9.1.6 I installed version 0.3.9 (manually. It seems the app is no more published on apps.owncloud.org)

**Comment by leonklingele** [comment]
Thanks for reporting this. I no longer test the app with ownCloud.
You need to run Nextcloud if you want to use a tested & stable version.

I will however do my best to get it running with ownCloud (probably
next week).

**Comment by leonklingele** [comment]
ownCloud (once again) has changed their file selector API. I'm no
longer going to implement workarounds for that.
Everything else still should work fine.

If you can live with a half-working featureset, simply increase the
`max-version` in this app's `appinfo/info.xml` file and you can
still use spreedme with the latest ownCloud.

```patch
diff --git a/appinfo/info.xml b/appinfo/info.xml
index ab56dcf..16ab5f9 100644
--- a/appinfo/info.xml
+++ b/appinfo/info.xml
@@ -17,7 +17,7 @@
     <repository type="git">https://github.com/strukturag/nextcloud-spreedme.git</repository>
     <ocsid>174436</ocsid>
     <dependencies>
-        <owncloud min-version="8.1" max-version="9.2" />
+        <owncloud min-version="8.1" max-version="10.0" />
         <nextcloud min-version="9" max-version="12" />
     </dependencies>
     <screenshot>https://raw.githubusercontent.com/strukturag/nextcloud-spreedme/master/screenshots/appstore/conference.gif</screenshot>
```

**Comment by danielepercivaldi** [comment]
Migrated to NC.
Thanks.
