### ISSUE TITLE
Nextcloud and Spreedme on different servers

### ISSUE THREAD

**Issue by Peter2121** [strukturag/nextcloud-spreedme#91]
I would like to move Spreedme from Nextcloud server (where it is actually installed) to another dedicated server. To overpass the problems, explained in [https://github.com/strukturag/nextcloud-spreedme/blob/master/doc/running-on-different-origins.md](url) I want to use Apache of Nextcloud server, just changing the destination in ProxyPass directive from 127.0.0.1:8080/webrtc to something else like 192.168.0.1:8080/webrtc. Are there another modifications to apply for such configuration?

**Comment by leonklingele** [comment]
No, it doesn't really matter where your spreed-webrtc installation
listens, as long as requests to it are correctly proxied by your
web server.

Just try it, see if it works, and report back if it doesn't :)

**Comment by Peter2121** [comment]
I confirm that it works correctly without additional tweaks.
