### ISSUE TITLE
Spreed issue after update to 0.3.11 / nexcloud

### ISSUE THREAD

**Issue by johnfelipe** [strukturag/nextcloud-spreedme#92]
https://goo.gl/h74sgJ

how can solve that?

**Comment by leonklingele** [comment]
Looks like you are/were using the `config/config.php` file to configure
the app. This configuration file is lost if you do an update of the app
via the web interface.
Please follow the new installation instructions to set up the app:
https://github.com/strukturag/nextcloud-spreedme#installation--setup-of-this-app
The new installation instructions do not necessarily rely on a
configuration file, but instead write the settings into the Nextcloud
database which remains across app updates, meaning you will not
reconfigure (i.e. restore the `config/config.php` file) after each
upgrade of this app. You can however still use the file-based way if
you prefer.

Let me know if this works for you.

**Comment by johnfelipe** [comment]
root@cloud:/var/www/nextcloud/apps/spreedme# find . -name "server.conf"
	root@cloud:/var/www/nextcloud/apps/spreedme# cd ..
	root@cloud:/var/www/nextcloud/apps# cd ..
	root@cloud:/var/www/nextcloud# find . -name "server.conf"

i cant find server.conf

**Comment by leonklingele** [comment]
`server.conf`? That's spreed-webrtc's config file. I was referring
to the `config/config.php` file of _this app_.
You most likely don't need to change that.

**Comment by johnfelipe** [comment]
then this:

	root@cloud:/var/www/nextcloud# cd /var/www/nextcloud/apps/spreedme/config
	root@cloud:/var/www/nextcloud/apps/spreedme/config# cp config.php.in config.php
	root@cloud:/var/www/nextcloud/apps/spreedme/config# nano config.php
	##
	; Minimal Spreed WebRTC configuration for Nextcloud

	[http]
	listen = 127.0.0.1:8080
	basePath = /webrtc/
	root = /usr/share/spreed-webrtc-server/www

	[app]
	sessionSecret = xxx
	encryptionSecret = xxx
	authorizeRoomJoin = true
	serverToken = xxx
	serverRealm = local
	extra = /var/www/nextcloud/apps/spreedme/extra
	plugin = extra/static/owncloud.js

	[users]
	enabled = true
	mode = sharedsecret
	sharedsecret_secret = xxxx

	##

how restart app?

**Comment by leonklingele** [comment]
That's not how you configure this app ;)
These lines should go into spreed-webrtc's server.conf file.

I'd suggest not to use the `config/config.php` approach, but instead
configure the app via Nextcloud's admin web interface.

If you still prefer to go the config-file-way, here's the template
for `config.php` which you'll need to adjust:
https://github.com/strukturag/nextcloud-spreedme/blob/master/config/config.php.in

**Comment by johnfelipe** [comment]
sorry im new in his nexcloud universe, share me instruction in how "configure the app via Nextcloud's admin web interface."

**Comment by johnfelipe** [comment]
Im in here https://cloud.votandoando.com/settings/admin/additional:
and put this:
https://goo.gl/Viih8b

**Comment by leonklingele** [comment]
Yes, and you need to copy that configuration to your spreed-webrtc
`server.conf`. How did you install spreed-webrtc?
Via the Ubuntu package? If so, you can find the file here:
`/etc/spreed/webrtc.conf`

Make sure to regenerate the Spreed WebRTC config as your secrets are
now public :)

**Comment by johnfelipe** [comment]
I cant find it, im using https://github.com/nextcloud/vm for install all enviroment

**Comment by leonklingele** [comment]
I'm now seeing a different error message on /apps/spreedme :
"Please log in into your Nextcloud account to use this service."
Please check if it works for you now.

The spreed-webrtc config file for snaps (which you are using) seems to
be located at `/var/snap/spreedme/current/server.conf`

**Comment by johnfelipe** [comment]
done, now how restart service or need to reboot all server...

**Comment by leonklingele** [comment]
Try `systemctl restart snap.spreedme.spreed-webrtc.service`
https://github.com/nextcloud/vm/blob/e2e0d478dc8059e5c59ebef4110cbf942931b7bc/apps/spreedme.sh#L119

**Comment by johnfelipe** [comment]
already done
tnks
