### ISSUE TITLE
nextcloud spreedme app + ios spreed.me client in 

### ISSUE THREAD

**Issue by miconx** [strukturag/nextcloud-spreedme#94]
i use ios spreed.me v2.2.8 and i try to connect it to our nextcloud instance of spreedme 
the url i used:
https://DOMAIN.TLD/apps/spreedme?tp=702312007940
(for temporary password ) 

and 
https://nextcloud.sportclinic.at/apps/spreedme

but after entering any url in the "address of the spreedbox" menu the app "restarts" and shows the initial screen (where i have to tap on the little arrow in order to open the "spreedbox-mode" again ....

**Comment by leonklingele** [comment]
@Ivansss can you please try to reproduce this issue with the URL provided above?

**Comment by miconx** [comment]
any solution / tipps available???
thanks

**Comment by Ivansss** [comment]
Sorry for the late reply, I have been on holidays.
The Spreed.ME iOS app does not support login with temporary passwords.
It requires the credentials of a Nextcloud user of your instance to be used.
Have you tried setting https://nextcloud.sportclinic.at as url?
After this, a login screen should be displayed and there you need to set the credentials of a Nextcloud user of your instance.

**Comment by miconx** [comment]
ok its working - i did not realise this - i thought the app "crashes" because it suddenly restarts and showed me the login form 
thanks for help
