### ISSUE TITLE
Some (at least static) content leaks out from the app 

### ISSUE THREAD

**Issue by kaksikanaa** [strukturag/nextcloud-spreedme#95]
We have discovered that for example user modified user icons (images) are shown outside the NC + Spreed.ME session for anyone who knows the right url's. For example:

https://your-cloud-domain/webrtc/static/img/buddy/s46/aaaaaaaa9eea-_9GqIbT/2bz0rbys_vAU/picture.png

Same happens with logos, for example:
https://your-cloud-domain/webrtc/extra/static/ver=1501960566/img/logo-512x512.png

We have:
NC 11.0.3
Spreed server version 0.29.6
Spreed app version 0.32

The NC and spreedme server has been installed after every know guide or tip and this bug has been verified on two separate systems (other is NC 12.02).

Is this a bug or do we have misconfiguration in our setup somewhere?

**Comment by kaksikanaa** [comment]
So this could be the nc server issue
https://github.com/nextcloud/server/issues/6418

**Comment by leonklingele-work** [comment]
This is not an issue as the URLs are unguessable. See https://www.schneier.com/blog/archives/2015/07/googles_unguess.html

**Comment by leonklingele-work** [comment]
> Same happens with logos

Leaking logos is fine imo. Don't you agree @kaksikanaa ?

**Comment by kaksikanaa** [comment]
Thanks for the quick reply and clarification and sorry for the duplicate issue here.
... I still do not understand why the user, service or app specific icons, logos etc. should be shown/available outside the active sessions at all.

**Comment by leonklingele-work** [comment]
Hey @kaksikanaa, did you read the article linked before?
Gist of it: URL is public but unguessable -> no one will be able to access it. The gibberish (`aaaaaaaa9eea-_9GqIbT/2bz0rbys_vAU`) serves as an access "password". It makes things easier to develop than to have strict user-session authentication and authorization checks when accessing a resource.

__EDIT__:
Fix typo.

**Comment by kaksikanaa** [comment]
Yes, but thanks for guiding me to even more better understanding on the subject :-)
