### ISSUE TITLE
SOFTWARE UPDATE NC12

### ISSUE THREAD

**Issue by rferreiroa** [strukturag/nextcloud-spreedme#96]
I tried to update with the steps described in Software Update section in the Spreedbox github, but when i try to update, i receive this message:
Exception: Updates between multiple major versions and downgrades are unsupported.

And now, i dont know how to do really. I wuld aprecciate some automatic installation if it´s possible.

:(
Kind regards

**Comment by leonklingele-work** [comment]
Duplicate of https://github.com/strukturag/nextcloud-spreedme/issues/96
